[_]
schema-version = "0.2"

[io.buildpacks]
builder = "paketobuildpacks/builder-jammy-base"

[[io.buildpacks.group]]
id = "paketo-buildpacks/python"

[[io.buildpacks.build.env]]
name = "BP_CPYTHON_VERSION"
value = "3.12"

[[io.buildpacks.launch.env]]
name = "PORT"
value = "3000"

[[io.buildpacks.launch.env]]
name = "DAGSTER_HOME"
value = "/workspace"

[[io.buildpacks.launch.env]]
name = "PYTHONPATH"
value = "/workspace/src"
