[project]
name = "data-analyst"
version = "0.1.0"
requires-python = ">=3.12,<3.13"
dependencies = [
    "fastapi",
    "hypercorn",
    "pydantic",
    "restate-sdk==0.14.0",
    "smolagents",
    "litellm",
    "duckdb",
    "polars",
    "httpx",
    "python-dotenv",
    "dag-tools @ git+https://github.com/edgy-solutions/dag-tools.git@master",
    "pyjwt[crypto]",
    "acryl-datahub",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
