# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions


from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ClassifyDomainIntent(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.SemanticResolution:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ClassifyDomainIntent", llm_response=llm_response, mode="request")
        return typing.cast(types.SemanticResolution, __result__)

    def ClassifyLegacyTable(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.TableClassificationResult:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ClassifyLegacyTable", llm_response=llm_response, mode="request")
        return typing.cast(types.TableClassificationResult, __result__)

    def DecomposeQuery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.SupervisorTaskPlan:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="DecomposeQuery", llm_response=llm_response, mode="request")
        return typing.cast(types.SupervisorTaskPlan, __result__)

    def DesignUI(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.DashboardUI:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="DesignUI", llm_response=llm_response, mode="request")
        return typing.cast(types.DashboardUI, __result__)

    def ExtractIntent(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ExtractedIntent:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractIntent", llm_response=llm_response, mode="request")
        return typing.cast(types.ExtractedIntent, __result__)

    def FormatGraphResponse(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.GraphExpertResponse:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="FormatGraphResponse", llm_response=llm_response, mode="request")
        return typing.cast(types.GraphExpertResponse, __result__)

    def FormatKnowledgeResponse(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.KnowledgeResponse:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="FormatKnowledgeResponse", llm_response=llm_response, mode="request")
        return typing.cast(types.KnowledgeResponse, __result__)

    def IterateBPMNGraph(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.BPMNInterviewState:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="IterateBPMNGraph", llm_response=llm_response, mode="request")
        return typing.cast(types.BPMNInterviewState, __result__)

    def RenderAsChart(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ChartUI:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="RenderAsChart", llm_response=llm_response, mode="request")
        return typing.cast(types.ChartUI, __result__)

    def RenderAsHazard(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.HazardUI:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="RenderAsHazard", llm_response=llm_response, mode="request")
        return typing.cast(types.HazardUI, __result__)

    def RenderAsMetric(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.MetricUI:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="RenderAsMetric", llm_response=llm_response, mode="request")
        return typing.cast(types.MetricUI, __result__)

    def RenderAsTopology(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.TopologyUI:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="RenderAsTopology", llm_response=llm_response, mode="request")
        return typing.cast(types.TopologyUI, __result__)

    def RouteAndPlan(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.MeshRoutingDecision:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="RouteAndPlan", llm_response=llm_response, mode="request")
        return typing.cast(types.MeshRoutingDecision, __result__)

    def SynthesizeReports(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.FinalSynthesis:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="SynthesizeReports", llm_response=llm_response, mode="request")
        return typing.cast(types.FinalSynthesis, __result__)

    def VerifyVerbChoice(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.VerbVerificationResult:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="VerifyVerbChoice", llm_response=llm_response, mode="request")
        return typing.cast(types.VerbVerificationResult, __result__)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ClassifyDomainIntent(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.SemanticResolution:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ClassifyDomainIntent", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.SemanticResolution, __result__)

    def ClassifyLegacyTable(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.TableClassificationResult:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ClassifyLegacyTable", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.TableClassificationResult, __result__)

    def DecomposeQuery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.SupervisorTaskPlan:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="DecomposeQuery", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.SupervisorTaskPlan, __result__)

    def DesignUI(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.DashboardUI:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="DesignUI", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.DashboardUI, __result__)

    def ExtractIntent(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ExtractedIntent:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractIntent", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ExtractedIntent, __result__)

    def FormatGraphResponse(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.GraphExpertResponse:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="FormatGraphResponse", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.GraphExpertResponse, __result__)

    def FormatKnowledgeResponse(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.KnowledgeResponse:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="FormatKnowledgeResponse", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.KnowledgeResponse, __result__)

    def IterateBPMNGraph(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.BPMNInterviewState:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="IterateBPMNGraph", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.BPMNInterviewState, __result__)

    def RenderAsChart(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ChartUI:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="RenderAsChart", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ChartUI, __result__)

    def RenderAsHazard(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.HazardUI:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="RenderAsHazard", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.HazardUI, __result__)

    def RenderAsMetric(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.MetricUI:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="RenderAsMetric", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.MetricUI, __result__)

    def RenderAsTopology(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.TopologyUI:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="RenderAsTopology", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.TopologyUI, __result__)

    def RouteAndPlan(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.MeshRoutingDecision:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="RouteAndPlan", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.MeshRoutingDecision, __result__)

    def SynthesizeReports(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.FinalSynthesis:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="SynthesizeReports", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.FinalSynthesis, __result__)

    def VerifyVerbChoice(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.VerbVerificationResult:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="VerifyVerbChoice", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.VerbVerificationResult, __result__)

    