# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions


from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ClassifySustainmentIntent(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.SemanticResolution:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ClassifySustainmentIntent", llm_response=llm_response, mode="request")
        return typing.cast(types.SemanticResolution, __result__)

    def DecomposeQuery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.SupervisorTaskPlan:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="DecomposeQuery", llm_response=llm_response, mode="request")
        return typing.cast(types.SupervisorTaskPlan, __result__)

    def DesignUI(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.DashboardUI:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="DesignUI", llm_response=llm_response, mode="request")
        return typing.cast(types.DashboardUI, __result__)

    def FormatGraphResponse(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.GraphExpertResponse:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="FormatGraphResponse", llm_response=llm_response, mode="request")
        return typing.cast(types.GraphExpertResponse, __result__)

    def FormatKnowledgeResponse(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.KnowledgeResponse:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="FormatKnowledgeResponse", llm_response=llm_response, mode="request")
        return typing.cast(types.KnowledgeResponse, __result__)

    def IterateBPMNGraph(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.BPMNInterviewState:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="IterateBPMNGraph", llm_response=llm_response, mode="request")
        return typing.cast(types.BPMNInterviewState, __result__)

    def RouteAndPlan(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.MeshRoutingDecision:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="RouteAndPlan", llm_response=llm_response, mode="request")
        return typing.cast(types.MeshRoutingDecision, __result__)

    def SynthesizeReports(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.FinalSynthesis:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="SynthesizeReports", llm_response=llm_response, mode="request")
        return typing.cast(types.FinalSynthesis, __result__)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ClassifySustainmentIntent(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.SemanticResolution:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ClassifySustainmentIntent", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.SemanticResolution, __result__)

    def DecomposeQuery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.SupervisorTaskPlan:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="DecomposeQuery", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.SupervisorTaskPlan, __result__)

    def DesignUI(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.DashboardUI:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="DesignUI", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.DashboardUI, __result__)

    def FormatGraphResponse(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.GraphExpertResponse:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="FormatGraphResponse", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.GraphExpertResponse, __result__)

    def FormatKnowledgeResponse(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.KnowledgeResponse:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="FormatKnowledgeResponse", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.KnowledgeResponse, __result__)

    def IterateBPMNGraph(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.BPMNInterviewState:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="IterateBPMNGraph", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.BPMNInterviewState, __result__)

    def RouteAndPlan(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.MeshRoutingDecision:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="RouteAndPlan", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.MeshRoutingDecision, __result__)

    def SynthesizeReports(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.FinalSynthesis:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="SynthesizeReports", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.FinalSynthesis, __result__)

    