# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions


from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ClassifySustainmentIntent(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.SemanticResolution:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ClassifySustainmentIntent", llm_response=llm_response, mode="request")
        return typing.cast(types.SemanticResolution, __result__)

    def DecomposeQuery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.SupervisorTaskPlan:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="DecomposeQuery", llm_response=llm_response, mode="request")
        return typing.cast(types.SupervisorTaskPlan, __result__)

    def DesignUI(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["types.TopologyUI", "types.HazardUI", "types.MetricUI", "types.DocumentUI"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="DesignUI", llm_response=llm_response, mode="request")
        return typing.cast(typing.Union["types.TopologyUI", "types.HazardUI", "types.MetricUI", "types.DocumentUI"], __result__)

    def FormatGraphResponse(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.GraphExpertResponse:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="FormatGraphResponse", llm_response=llm_response, mode="request")
        return typing.cast(types.GraphExpertResponse, __result__)

    def SynthesizeReports(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.FinalSynthesis:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="SynthesizeReports", llm_response=llm_response, mode="request")
        return typing.cast(types.FinalSynthesis, __result__)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ClassifySustainmentIntent(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.SemanticResolution:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ClassifySustainmentIntent", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.SemanticResolution, __result__)

    def DecomposeQuery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.SupervisorTaskPlan:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="DecomposeQuery", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.SupervisorTaskPlan, __result__)

    def DesignUI(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["stream_types.TopologyUI", "stream_types.HazardUI", "stream_types.MetricUI", "stream_types.DocumentUI"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="DesignUI", llm_response=llm_response, mode="stream")
        return typing.cast(typing.Union["stream_types.TopologyUI", "stream_types.HazardUI", "stream_types.MetricUI", "stream_types.DocumentUI"], __result__)

    def FormatGraphResponse(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.GraphExpertResponse:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="FormatGraphResponse", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.GraphExpertResponse, __result__)

    def SynthesizeReports(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.FinalSynthesis:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="SynthesizeReports", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.FinalSynthesis, __result__)

    