# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (18)
# #########################################################################

class AgentResponse(BaseModel):
    # The universal response payload returned by every agent pod.
# The Dagster orchestrator inspects this to decide on next steps
# (e.g., retry, escalate, or continue the pipeline).
    status: typing.Optional[types.AgentStatus] = Field(default=None, description='Outcome of the agent\'s execution.')
    summary: typing.Optional[str] = Field(default=None, description='Brief human-readable summary of what the agent did.')
    extracted_metrics: typing.Dict[str, float] = Field(description='Key-value pairs of domain metrics extracted during processing.')

class AgentTask(BaseModel):
    # The universal task payload sent from the Dagster orchestrator to any agent
# pod via HTTP POST. Every agent endpoint must accept this schema.
    task_description: typing.Optional[str] = Field(default=None, description='Human-readable description of the work the agent should perform.')
    dataset_id: typing.Optional[str] = Field(default=None, description='Identifier for the target dataset or data asset in the mesh.')
    semantic_context: typing.Optional["SemanticResolution"] = Field(default=None, description='Optional pre-resolved semantic context. When present, agents can skip their own classification step.')

class AgentTaskDefinition(BaseModel):
    target_persona: typing.Optional[types.PersonaTarget] = None
    sub_query: typing.Optional[str] = None

class AuditResponse(BaseModel):
    non_compliant_nodes: typing.List[str]
    rule_violated: typing.Optional[str] = None
    recommended_fix: typing.Optional[str] = None

class AuthoringResponse(BaseModel):
    draft_content: typing.Optional[str] = Field(default=None, description='A clear, formatted Markdown summary of the requested technical data. Do NOT use XML.')
    missing_info_flags: typing.List[str] = Field(description='List of any required technical data that was missing from the graph.')

class DashboardUI(BaseModel):
    components: typing.List[typing.Union["TopologyUI", "HazardUI", "MetricUI", "DocumentUI"]]

class DocumentUI(BaseModel):
    archetype: typing.Optional[types.SemanticArchetype] = Field(default=None, description='MUST be KNOWLEDGE_DOCUMENT')
    subject_concept: typing.Optional[str] = None
    markdown_content: typing.Optional[str] = None

class FinalSynthesis(BaseModel):
    markdown_report: typing.Optional[str] = None

class GraphExpertResponse(BaseModel):
    confidence_score: typing.Optional[float] = None
    referenced_uris: typing.List[str]
    data: typing.Optional[typing.Union["MechanicResponse", "AuthoringResponse", "LogisticsResponse", "AuditResponse"]] = None

class HazardUI(BaseModel):
    archetype: typing.Optional[types.SemanticArchetype] = Field(default=None, description='MUST be HAZARD_DECLARATION')
    subject_concept: typing.Optional[str] = None
    severity: typing.Optional[types.SeverityLevel] = None
    hazards: typing.List["UIEntity"]

class LogisticsResponse(BaseModel):
    impacted_platforms: typing.List[str]
    blocked_procedures: typing.List[str]
    risk_severity: typing.Optional[str] = None

class MechanicResponse(BaseModel):
    tool_list: typing.List[str]
    safety_warnings: typing.List[str]
    short_answer: typing.Optional[str] = None

class MetricUI(BaseModel):
    archetype: typing.Optional[types.SemanticArchetype] = Field(default=None, description='MUST be ASSET_STATE_METRIC')
    subject_concept: typing.Optional[str] = None
    metrics: typing.List["UIEntity"]

class SemanticResolution(BaseModel):
    # Result of mapping free-text input to a canonical sustainment concept.
# The resolved_uri is a dynamic ontology URI (not a hardcoded enum) that
# comes from the RDF graph at runtime.
    resolved_uri: typing.Optional[str] = Field(default=None, description='The ontology URI that best matches the input query. Must be one of the URIs provided in active_ontology_classes.')
    confidence_score: typing.Optional[float] = Field(default=None, description='Model confidence in the match, between 0.0 and 1.0.')
    suggested_dbt_models: typing.List[str] = Field(description='Ordered list of dbt model names relevant to the resolved concept.')

class SupervisorTaskPlan(BaseModel):
    tasks: typing.List["AgentTaskDefinition"]
    reasoning: typing.Optional[str] = None

class TopologyUI(BaseModel):
    archetype: typing.Optional[types.SemanticArchetype] = Field(default=None, description='MUST be PROCESS_TOPOLOGY')
    subject_concept: typing.Optional[str] = None
    nodes: typing.List["UIEntity"]
    edges: typing.List["UIRelation"]

class UIEntity(BaseModel):
    id: typing.Optional[str] = None
    name: typing.Optional[str] = None
    type: typing.Optional[str] = None
    description: typing.Optional[str] = None

class UIRelation(BaseModel):
    source: typing.Optional[str] = None
    target: typing.Optional[str] = None
    relation: typing.Optional[str] = None
    predicate: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
