# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (64)
# #########################################################################

class AgentResponse(BaseModel):
    # The universal response payload returned by every agent pod.
# The Dagster orchestrator inspects this to decide on next steps
# (e.g., retry, escalate, or continue the pipeline).
    status: typing.Optional[types.AgentStatus] = Field(default=None, description='Outcome of the agent\'s execution.')
    summary: typing.Optional[str] = Field(default=None, description='Brief human-readable summary of what the agent did.')
    structured_data: typing.Optional[str] = Field(default=None, description='MUST be a raw JSON object/dictionary containing the actual data (e.g., lists of dashboards, chart metrics). DO NOT stringify this inside summary.')
    extracted_metrics: typing.Dict[str, float] = Field(description='Key-value pairs of domain metrics extracted during processing.')
    execution_trace: typing.Optional[str] = Field(default=None, description='The internal reasoning logs or trajectory of the agent.')

class AgentTask(BaseModel):
    # The universal task payload sent from the Dagster orchestrator to any agent
# pod via HTTP POST. Every agent endpoint must accept this schema.
    task_description: typing.Optional[str] = Field(default=None, description='Human-readable description of the work the agent should perform.')
    dataset_id: typing.Optional[str] = Field(default=None, description='Identifier for the target dataset or data asset in the mesh.')
    semantic_context: typing.Optional["SemanticResolution"] = Field(default=None, description='Optional pre-resolved semantic context. When present, agents can skip their own classification step.')
    user_id: typing.Optional[str] = Field(default=None, description='The identity of the user requesting the task, used for memory partitioning.')

class AgentTaskDefinition(BaseModel):
    target_persona: typing.Optional[typing.Union[types.PersonaTarget, str]] = None
    sub_query: typing.Optional[str] = None

class AnomalyNode(BaseModel):
    element_id: typing.Optional[str] = Field(default=None, description='e.g., TR-1042')
    temp: typing.Optional[float] = None
    status: typing.Optional[str] = Field(default=None, description='DEGRADED or CRITICAL_FAILURE')

class AuditResponse(BaseModel):
    non_compliant_nodes: typing.List[str]
    rule_violated: typing.Optional[str] = None
    recommended_fix: typing.Optional[str] = None

class AuthoringResponse(BaseModel):
    draft_content: typing.Optional[str] = Field(default=None, description='A clear, formatted Markdown summary of the requested technical data. Do NOT use XML.')
    missing_info_flags: typing.List[str] = Field(description='List of any required technical data that was missing from the graph.')

class BPMNEdge(BaseModel):
    source_id: typing.Optional[str] = Field(default=None, description='The id of the source BPMNNode.')
    target_id: typing.Optional[str] = Field(default=None, description='The id of the target BPMNNode.')
    condition_expression: typing.Optional[str] = Field(default=None, description='For edges leaving an ExclusiveGateway, the boolean condition that activates this path. Null for unconditional flows.')

class BPMNInterviewState(BaseModel):
    nodes: typing.List["BPMNNode"] = Field(description='The full list of BPMN nodes in the current graph. Updated cumulatively on each turn.')
    edges: typing.List["BPMNEdge"] = Field(description='The full list of edges connecting nodes. Updated cumulatively on each turn.')
    unresolved_paths: typing.List[str] = Field(description='Human-readable descriptions of dead-end paths, missing connections, or ambiguities that need user input to resolve. E.g. \'Gateway gw_1 has no outgoing edge for the FALSE branch.\'')
    is_ready_to_compile: typing.Optional[bool] = Field(default=None, description='True ONLY when: (1) there are zero unresolved_paths, (2) every ServiceTask has ontology_class and data_source filled, (3) the user has explicitly confirmed the workflow is complete. Default to false.')
    agent_reply: typing.Optional[str] = Field(default=None, description='Natural language response to the user. This is the conversational text shown in the Neural Stream.')

class BPMNNode(BaseModel):
    id: typing.Optional[str] = Field(default=None, description='Unique identifier for this node, e.g. \'task_1\', \'gw_1\', \'timer_1\'.')
    name: typing.Optional[str] = Field(default=None, description='Human-readable label for this node, e.g. \'Ingest Engine Telemetry\'.')
    node_type: typing.Optional[types.BPMNNodeType] = Field(default=None, description='The BPMN element type.')
    ontology_class: typing.Optional[str] = Field(default=None, description='IOF-MRO / MIMOSA ontology URI grounding this node. REQUIRED for ServiceTask, null for others. Must come from the available_ontology_classes list.')
    data_source: typing.Optional[str] = Field(default=None, description='DataHub / dbt model name grounding this node. REQUIRED for ServiceTask, null for others. Must come from the available_data_sources list.')

class CapabilityPath(BaseModel):
    capability: typing.Optional[str] = None

class ChartUI(BaseModel):
    archetype: typing.Optional[types.SemanticArchetype] = Field(default=None, description='MUST be CHART_WIDGET')
    source_persona: typing.Optional[str] = None
    subject_concept: typing.Optional[str] = None
    chart_type: typing.Optional[types.ChartType] = None
    chart_data: typing.Optional[str] = Field(default=None, description='JSON stringified array of data points for Recharts preview.')
    sql_query: typing.Optional[str] = Field(default=None, description='The raw SQL query used. Required for Superset publication.')
    superset_dataset_name: typing.Optional[str] = None
    is_published: typing.Optional[bool] = None

class CompareScenarios(BaseModel):
    a: typing.Optional[str] = None
    b: typing.Optional[str] = None

class CoverageGap(BaseModel):
    placeholder: typing.Optional[str] = None

class DashboardUI(BaseModel):
    components: typing.List[typing.Union["TopologyUI", "HazardUI", "MetricUI", "DocumentUI", "ChartUI", "DigitalTwinUI"]]

class DataStewardResponse(BaseModel):
    tool_list: typing.List[str]
    safety_warnings: typing.List[str]
    short_answer: typing.Optional[str] = None

class DeltaEffect(BaseModel):
    metric: typing.Optional[str] = None
    direction: typing.Optional[str] = None
    magnitude: typing.Optional[str] = None
    affected: typing.List[str]

class DeltaSetUI(BaseModel):
    archetype: typing.Optional[str] = Field(default=None, description='MUST be DELTA_SET')
    source_persona: typing.Optional[str] = None
    subject_concept: typing.Optional[str] = None
    effects: typing.List["DeltaEffect"]
    scope_label: typing.Optional[str] = None
    baseline_label: typing.Optional[str] = None
    headline: typing.Optional[str] = None

class DigitalTwinUI(BaseModel):
    archetype: typing.Optional[types.SemanticArchetype] = Field(default=None, description='MUST be DIGITAL_TWIN_3D')
    source_persona: typing.Optional[str] = None
    subject_concept: typing.Optional[str] = None
    device_id: typing.Optional[str] = Field(default=None, description='Name of the system, e.g., LTAMDS Gen-4')
    core_temp: typing.Optional[float] = Field(default=None, description='Overall core temperature of the system')
    uptime_hours: typing.Optional[int] = None
    anomalies: typing.List["AnomalyNode"] = Field(description='List of elements that are not nominal')

class DocumentUI(BaseModel):
    archetype: typing.Optional[types.SemanticArchetype] = Field(default=None, description='MUST be KNOWLEDGE_DOCUMENT')
    source_persona: typing.Optional[str] = Field(default=None, description='The persona that produced this data. Copy from the raw data \'persona\' field.')
    subject_concept: typing.Optional[str] = None
    markdown_content: typing.Optional[str] = None

class DownstreamOf(BaseModel):
    project: typing.Optional[str] = None
    direction: typing.Optional[str] = None

class ExtractedIntent(BaseModel):
    mode: typing.Optional[types.Mode] = None
    entity_refs: typing.List[str] = Field(description='Concrete entities, parts, systems, datasets the user mentioned (e.g., \'Auxiliary Fuel Pump\', \'C-130 hydraulic system\'). Empty if the query has no specific referents.')
    confidence: typing.Optional[float] = Field(default=None, description='Confidence in the mode choice.')
    reasoning: typing.Optional[str] = Field(default=None, description='Why this mode — for observability and debugging.')

class FinalSynthesis(BaseModel):
    markdown_report: typing.Optional[str] = None

class GraphExpertResponse(BaseModel):
    confidence_score: typing.Optional[float] = None
    referenced_uris: typing.List[str]
    data: typing.Optional[typing.Union["MechanicResponse", "AuthoringResponse", "LogisticsResponse", "AuditResponse", "DataStewardResponse"]] = None
    execution_trace: typing.Optional[str] = Field(default=None, description='The internal reasoning logs or trajectory of the agent.')

class HazardUI(BaseModel):
    archetype: typing.Optional[types.SemanticArchetype] = Field(default=None, description='MUST be HAZARD_DECLARATION')
    source_persona: typing.Optional[str] = Field(default=None, description='The persona that produced this data. Copy from the raw data \'persona\' field.')
    subject_concept: typing.Optional[str] = None
    severity: typing.Optional[types.SeverityLevel] = None
    hazards: typing.List["UIEntity"]

class IntervalRow(BaseModel):
    group_kind: typing.Optional[str] = None
    group_id: typing.Optional[str] = None
    group_name: typing.Optional[str] = None
    group_weight: typing.Optional[float] = None
    initiative_id: typing.Optional[str] = None
    initiative_name: typing.Optional[str] = None
    phase_id: typing.Optional[str] = None
    phase_name: typing.Optional[str] = None
    phase_sequence: typing.Optional[int] = None
    project_id: typing.Optional[str] = None
    project_name: typing.Optional[str] = None
    planned_start: typing.Optional[str] = None
    planned_end: typing.Optional[str] = None
    actual_start: typing.Optional[str] = None
    actual_end: typing.Optional[str] = None
    risk_flag: typing.Optional[str] = None

class KnowledgeResponse(BaseModel):
    summary: typing.Optional[str] = Field(default=None, description='A clear, professional summary answering the user\'s knowledge or policy question. Format in Markdown.')
    referenced_documents: typing.List[str] = Field(description='List of manual sections, policies, or documents cited in the summary.')
    confidence_score: typing.Optional[float] = None
    execution_trace: typing.Optional[str] = Field(default=None, description='The internal reasoning logs or trajectory of the agent.')

class LogisticsResponse(BaseModel):
    impacted_platforms: typing.List[str]
    blocked_procedures: typing.List[str]
    risk_severity: typing.Optional[str] = None

class MatrixCell(BaseModel):
    row_id: typing.Optional[str] = None
    column_id: typing.Optional[str] = None
    level: typing.Optional[float] = None
    target_level: typing.Optional[float] = None
    gap: typing.Optional[float] = None

class MatrixGridUI(BaseModel):
    archetype: typing.Optional[str] = Field(default=None, description='MUST be MATRIX_GRID')
    source_persona: typing.Optional[str] = None
    subject_concept: typing.Optional[str] = None
    rows: typing.List["MatrixCell"]
    level_label: typing.Optional[str] = None
    scope_label: typing.Optional[str] = None
    as_of: typing.Optional[str] = None

class MaturityGrid(BaseModel):
    as_of: typing.Optional[str] = None

class MechanicResponse(BaseModel):
    tool_list: typing.List[str]
    safety_warnings: typing.List[str]
    short_answer: typing.Optional[str] = None

class MeshRoutingDecision(BaseModel):
    intent: typing.Optional[typing.Union[types.Intent, str]] = None
    domain: typing.Optional[typing.Union[types.Domain, str]] = None
    confidence: typing.Optional[float] = Field(default=None, description='Confidence in both intent and domain classification.')
    reasoning: typing.Optional[str] = Field(default=None, description='Why you routed it this way.')
    task_plan: typing.Optional["SupervisorTaskPlan"] = Field(default=None, description='Populate for all operational intents (queries, creation, retrieval, audits) to seed the multi-agent execution.')

class MetricUI(BaseModel):
    archetype: typing.Optional[types.SemanticArchetype] = Field(default=None, description='MUST be ASSET_STATE_METRIC')
    source_persona: typing.Optional[str] = Field(default=None, description='The persona that produced this data. Copy from the raw data \'persona\' field.')
    subject_concept: typing.Optional[str] = None
    metrics: typing.List["UIEntity"]

class MoveProject(BaseModel):
    project: typing.Optional[str] = None
    when: typing.Optional[str] = None

class NoIntentMatch(BaseModel):
    nearest_intent_id: typing.Optional[str] = None
    nearest_rejected_because: typing.Optional[str] = None
    out_of_model_concept: typing.Optional[str] = None
    reason: typing.Optional[str] = None

class NotComputableInFamily(BaseModel):
    out_of_model_concept: typing.Optional[str] = None
    reason: typing.Optional[str] = None

class PeriodSeriesRow(BaseModel):
    period: typing.Optional[str] = None
    capex: typing.Optional[float] = None
    expense: typing.Optional[float] = None
    total: typing.Optional[float] = None
    cap: typing.Optional[float] = None
    over_cap: typing.Optional[bool] = None
    overage: typing.Optional[float] = None

class PeriodSeriesUI(BaseModel):
    archetype: typing.Optional[str] = Field(default=None, description='MUST be PERIOD_SERIES')
    source_persona: typing.Optional[str] = None
    subject_concept: typing.Optional[str] = None
    rows: typing.List["PeriodSeriesRow"]
    scope_label: typing.Optional[str] = None
    value_unit: typing.Optional[str] = None

class PlatformScope(BaseModel):
    platforms: typing.List[str] = Field(description='Catalog platform slugs the user wants to restrict to, normalized to the KNOWN list (e.g. \'snowflake\', \'postgres\'). Empty when no platform was asked for. A platform the user named that is NOT in the known list does NOT go here — it goes in `unrecognized`.')
    platform_mentioned: typing.Optional[bool] = Field(default=None, description='True iff the user named or clearly implied a specific platform to filter by (\'snowflake tables\', \'which warehouse feeds X\'). False for platform-agnostic lineage questions (\'what feeds X\', \'upstream of X\').')
    unrecognized: typing.List[str] = Field(description='Any platform token the user named that is NOT in the known-platforms list. Lets the caller say \'that isn\'t a catalog platform\' instead of silently returning everything. Empty when the mentioned platform(s) are all recognized, or when none was mentioned.')
    reasoning: typing.Optional[str] = Field(default=None, description='One sentence — for observability.')

class PredicateClassification(BaseModel):
    resolved_verb_iri: typing.Optional[typing.Union[types.Predicate, str]] = Field(default=None, description='The verb IRI that best matches the user\'s intent given the resolved subject. Must be one of the IRIs provided in the dynamic enum.')
    confidence_score: typing.Optional[float] = Field(default=None, description='0.0 (no fit) to 1.0 (clear fit). The supervisor\'s PREDICATE_FALLBACK_SCORE_THRESHOLD env var thresholds against this.')
    reasoning: typing.Optional[str] = Field(default=None, description='One sentence on why this verb was picked given the query and subject. If subject_uri == \'UNKNOWN\', explain the pick against query alone.')

class ProcessEvolution(BaseModel):
    process: typing.Optional[str] = None

class ProjectsIn(BaseModel):
    window: typing.Optional[str] = None
    scope: typing.Optional[str] = None

class SPOInterviewTurn(BaseModel):
    agent_reply: typing.Optional[str] = Field(default=None, description='Conversational text to the user (2-5 sentences). If you refused a pick or something was out-of-set, explain and offer the closest legal options.')
    pick: typing.Optional["SPOPick"] = Field(default=None, description='The structured pick for this turn. Use action=NoPick (with the question in agent_reply) when you are still clarifying.')

class SPOPick(BaseModel):
    action: typing.Optional[types.SPOPickAction] = None
    workflow_id: typing.Optional[str] = Field(default=None, description='snake_case id, e.g. \'promote_answer_artifact\'. Only for SetMetadata.')
    workflow_name: typing.Optional[str] = Field(default=None, description='Human-readable name. Only for SetMetadata.')
    classification: typing.Optional[str] = Field(default=None, description='The workflow\'s declared domain / compartment, e.g. \'DATA_ENGINEERING\'. Gates who may observe and scopes the verb question. Only for SetMetadata.')
    subject_uri: typing.Optional[str] = Field(default=None, description='An EXACT value copied verbatim from available_subjects. NEVER invent or paraphrase one.')
    verb_iri: typing.Optional[str] = Field(default=None, description='An EXACT value copied verbatim from available_verbs (which are the verbs compatible with the focused subject). NEVER invent one.')
    audience: typing.Optional[str] = Field(default=None, description='An EXACT value copied verbatim from available_audiences.')
    step_title: typing.Optional[str] = Field(default=None, description='Short title shown to the approver. Optional.')
    step_summary: typing.Optional[str] = Field(default=None, description='One-line summary shown to the approver. Optional.')
    endpoint: typing.Optional[str] = Field(default=None, description='The action endpoint (may contain {placeholders} bound at trigger time).')
    capability: typing.Optional[str] = Field(default=None, description='Topaz-decidable capability for the action, e.g. \'mesh:publishArtifact\'.')
    step_id: typing.Optional[str] = Field(default=None, description='Optional stable id for the step, e.g. \'approve_promotion\'.')

class SeedPortfolioCanvas(BaseModel):
    confirm: typing.Optional[bool] = Field(default=None, description='true when the ask is for the WHOLE board, not one measure')

class SemanticResolution(BaseModel):
    # Result of mapping free-text input to a canonical sustainment concept.
# The resolved_uri is a dynamic ontology URI (not a hardcoded enum) that
# comes from the RDF graph at runtime.
    resolved_uri: typing.Optional[typing.Union[types.OntologyClass, str]] = Field(default=None, description='The ontology URI that best matches the input query. Must be one of the URIs provided in active_ontology_classes.')
    confidence_score: typing.Optional[float] = Field(default=None, description='Model confidence in the match, between 0.0 and 1.0.')
    reasoning: typing.Optional[str] = Field(default=None, description='1-2 sentence explanation of why this class was chosen.')
    instance_identifier: typing.Optional[str] = Field(default=None, description='If the query refers to a SPECIFIC NAMED INDIVIDUAL — a catalog asset, a procedure or work-order code, a data module code (DMC), a tail number, an equipment serial, or a quoted or titled name — copy that exact token here verbatim, INCLUDING any qualifier the user gave it (schema, dataset or path prefix). The phone book normalizes qualifiers and matches on the asset\'s own name, so a qualified token is safer than a guessed bare one. Do NOT extract a word that merely APPEARS NEAR the asset name — a token lifted from the surrounding sentence rather than naming the thing will be refused as non-specific, and that refusal costs the whole answer. Otherwise leave null. This field gates the router\'s instance-resolution pre-step (Recipe v2): when set, the router fans the token out to registered providers and lets the authoritative phone-book class override resolved_uri. Still always resolve resolved_uri as your best guess either way — the phone book may miss.')

class SetCost(BaseModel):
    project: typing.Optional[str] = None
    kind: typing.Optional[str] = None
    period: typing.Optional[str] = None
    amount: typing.Optional[str] = None

class ShortfallGridUI(BaseModel):
    archetype: typing.Optional[str] = Field(default=None, description='MUST be SHORTFALL_GRID')
    source_persona: typing.Optional[str] = None
    subject_concept: typing.Optional[str] = None
    rows: typing.List["ShortfallRow"] = Field(description='THREE QUANTITIES, not two - required/committed/secured are distinct and a renderer that collapses them loses the answer.')
    value_label: typing.Optional[str] = None
    value_unit: typing.Optional[str] = None
    scope_label: typing.Optional[str] = None

class ShortfallRow(BaseModel):
    subject_id: typing.Optional[str] = None
    subject_name: typing.Optional[str] = None
    period: typing.Optional[str] = None
    required: typing.Optional[float] = None
    committed: typing.Optional[float] = None
    secured: typing.Optional[float] = None
    shortfall: typing.Optional[float] = None
    state: typing.Optional[str] = None

class ShowCostCurve(BaseModel):
    scope: typing.Optional[str] = None
    window: typing.Optional[str] = None
    kind: typing.Optional[str] = None
    over_cap_only: typing.Optional[bool] = None

class ShowFundingGap(BaseModel):
    group_by: typing.Optional[str] = None
    window: typing.Optional[str] = None

class ShowSiteLoad(BaseModel):
    site: typing.Optional[str] = None
    window: typing.Optional[str] = None
    over_threshold_only: typing.Optional[bool] = None

class SiteSchedule(BaseModel):
    site: typing.Optional[str] = None
    window: typing.Optional[str] = None

class SummarizeSession(BaseModel):
    placeholder: typing.Optional[str] = None

class SupervisorTaskPlan(BaseModel):
    tasks: typing.List["AgentTaskDefinition"]
    extracted_concepts: typing.List[str] = Field(description='List of main entities/components the user is asking about (e.g., \'Auxiliary Fuel Pump\', \'C-130\'). This populates the Ontology Map.')
    reasoning: typing.Optional[str] = None

class TableClassificationResult(BaseModel):
    resolved_uri: typing.Optional[typing.Union[types.OntologyClass, str]] = Field(default=None, description='The exact matching IOF Ontology URI, or null if uncertain/unrelated.')
    confidence_score: typing.Optional[float] = Field(default=None, description='Confidence level from 0.0 to 1.0.')
    reasoning: typing.Optional[str] = Field(default=None, description='A 1-2 sentence explanation of why this mapping was chosen based on the dossier.')

class TechFootprint(BaseModel):
    technology: typing.Optional[str] = None

class ThresholdCell(BaseModel):
    subject_id: typing.Optional[str] = None
    period: typing.Optional[str] = None
    value: typing.Optional[float] = None
    threshold: typing.Optional[float] = None
    over_threshold: typing.Optional[bool] = None

class ThresholdGridUI(BaseModel):
    archetype: typing.Optional[str] = Field(default=None, description='MUST be THRESHOLD_GRID')
    source_persona: typing.Optional[str] = None
    subject_concept: typing.Optional[str] = None
    rows: typing.List["ThresholdCell"]
    value_label: typing.Optional[str] = None
    scope_label: typing.Optional[str] = None

class TimelineUI(BaseModel):
    archetype: typing.Optional[str] = Field(default=None, description='MUST be INTERVAL_TIMELINE')
    source_persona: typing.Optional[str] = None
    subject_concept: typing.Optional[str] = None
    rows: typing.List["IntervalRow"] = Field(description='ROW KEY IS (group_id, project_id) - a project fans out to one row per capability contribution under the capability pivot, so project_id alone is NOT unique.')
    group_kind: typing.Optional[str] = Field(default=None, description='initiative | capability | target. Stated by the verb, NEVER inferred from the ids.')
    scope_label: typing.Optional[str] = None

class TopologyUI(BaseModel):
    archetype: typing.Optional[types.SemanticArchetype] = Field(default=None, description='MUST be PROCESS_TOPOLOGY')
    source_persona: typing.Optional[str] = Field(default=None, description='The persona that produced this data (e.g. MECHANIC, PROCESS_ENGINEER). Copy from the raw data \'persona\' field.')
    subject_concept: typing.Optional[str] = None
    nodes: typing.List["UIEntity"]
    edges: typing.List["UIRelation"]

class UIEntity(BaseModel):
    id: typing.Optional[str] = None
    name: typing.Optional[str] = None
    type: typing.Optional[str] = None
    description: typing.Optional[str] = None

class UIRelation(BaseModel):
    source: typing.Optional[str] = None
    target: typing.Optional[str] = None
    relation: typing.Optional[str] = None
    predicate: typing.Optional[str] = None

class WhatBlocks(BaseModel):
    project: typing.Optional[str] = None
    direction: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
