# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (29)
# #########################################################################

class AgentResponse(BaseModel):
    # The universal response payload returned by every agent pod.
# The Dagster orchestrator inspects this to decide on next steps
# (e.g., retry, escalate, or continue the pipeline).
    status: typing.Optional[types.AgentStatus] = Field(default=None, description='Outcome of the agent\'s execution.')
    summary: typing.Optional[str] = Field(default=None, description='Brief human-readable summary of what the agent did.')
    structured_data: typing.Optional[str] = Field(default=None, description='MUST be a raw JSON object/dictionary containing the actual data (e.g., lists of dashboards, chart metrics). DO NOT stringify this inside summary.')
    extracted_metrics: typing.Dict[str, float] = Field(description='Key-value pairs of domain metrics extracted during processing.')
    execution_trace: typing.Optional[str] = Field(default=None, description='The internal reasoning logs or trajectory of the agent.')

class AgentTask(BaseModel):
    # The universal task payload sent from the Dagster orchestrator to any agent
# pod via HTTP POST. Every agent endpoint must accept this schema.
    task_description: typing.Optional[str] = Field(default=None, description='Human-readable description of the work the agent should perform.')
    dataset_id: typing.Optional[str] = Field(default=None, description='Identifier for the target dataset or data asset in the mesh.')
    semantic_context: typing.Optional["SemanticResolution"] = Field(default=None, description='Optional pre-resolved semantic context. When present, agents can skip their own classification step.')
    user_id: typing.Optional[str] = Field(default=None, description='The identity of the user requesting the task, used for memory partitioning.')

class AgentTaskDefinition(BaseModel):
    target_persona: typing.Optional[typing.Union[types.PersonaTarget, str]] = None
    sub_query: typing.Optional[str] = None

class AnomalyNode(BaseModel):
    element_id: typing.Optional[str] = Field(default=None, description='e.g., TR-1042')
    temp: typing.Optional[float] = None
    status: typing.Optional[str] = Field(default=None, description='DEGRADED or CRITICAL_FAILURE')

class AuditResponse(BaseModel):
    non_compliant_nodes: typing.List[str]
    rule_violated: typing.Optional[str] = None
    recommended_fix: typing.Optional[str] = None

class AuthoringResponse(BaseModel):
    draft_content: typing.Optional[str] = Field(default=None, description='A clear, formatted Markdown summary of the requested technical data. Do NOT use XML.')
    missing_info_flags: typing.List[str] = Field(description='List of any required technical data that was missing from the graph.')

class BPMNEdge(BaseModel):
    source_id: typing.Optional[str] = Field(default=None, description='The id of the source BPMNNode.')
    target_id: typing.Optional[str] = Field(default=None, description='The id of the target BPMNNode.')
    condition_expression: typing.Optional[str] = Field(default=None, description='For edges leaving an ExclusiveGateway, the boolean condition that activates this path. Null for unconditional flows.')

class BPMNInterviewState(BaseModel):
    nodes: typing.List["BPMNNode"] = Field(description='The full list of BPMN nodes in the current graph. Updated cumulatively on each turn.')
    edges: typing.List["BPMNEdge"] = Field(description='The full list of edges connecting nodes. Updated cumulatively on each turn.')
    unresolved_paths: typing.List[str] = Field(description='Human-readable descriptions of dead-end paths, missing connections, or ambiguities that need user input to resolve. E.g. \'Gateway gw_1 has no outgoing edge for the FALSE branch.\'')
    is_ready_to_compile: typing.Optional[bool] = Field(default=None, description='True ONLY when: (1) there are zero unresolved_paths, (2) every ServiceTask has ontology_class and data_source filled, (3) the user has explicitly confirmed the workflow is complete. Default to false.')
    agent_reply: typing.Optional[str] = Field(default=None, description='Natural language response to the user. This is the conversational text shown in the Neural Stream.')

class BPMNNode(BaseModel):
    id: typing.Optional[str] = Field(default=None, description='Unique identifier for this node, e.g. \'task_1\', \'gw_1\', \'timer_1\'.')
    name: typing.Optional[str] = Field(default=None, description='Human-readable label for this node, e.g. \'Ingest Engine Telemetry\'.')
    node_type: typing.Optional[types.BPMNNodeType] = Field(default=None, description='The BPMN element type.')
    ontology_class: typing.Optional[str] = Field(default=None, description='IOF-MRO / MIMOSA ontology URI grounding this node. REQUIRED for ServiceTask, null for others. Must come from the available_ontology_classes list.')
    data_source: typing.Optional[str] = Field(default=None, description='DataHub / dbt model name grounding this node. REQUIRED for ServiceTask, null for others. Must come from the available_data_sources list.')

class ChartUI(BaseModel):
    archetype: typing.Optional[types.SemanticArchetype] = Field(default=None, description='MUST be CHART_WIDGET')
    source_persona: typing.Optional[str] = None
    subject_concept: typing.Optional[str] = None
    chart_type: typing.Optional[types.ChartType] = None
    chart_data: typing.Optional[str] = Field(default=None, description='JSON stringified array of data points for Recharts preview.')
    sql_query: typing.Optional[str] = Field(default=None, description='The raw SQL query used. Required for Superset publication.')
    superset_dataset_name: typing.Optional[str] = None
    is_published: typing.Optional[bool] = None

class DashboardUI(BaseModel):
    components: typing.List[typing.Union["TopologyUI", "HazardUI", "MetricUI", "DocumentUI", "ChartUI", "DigitalTwinUI"]]

class DataStewardResponse(BaseModel):
    tool_list: typing.List[str]
    safety_warnings: typing.List[str]
    short_answer: typing.Optional[str] = None

class DigitalTwinUI(BaseModel):
    archetype: typing.Optional[types.SemanticArchetype] = Field(default=None, description='MUST be DIGITAL_TWIN_3D')
    source_persona: typing.Optional[str] = None
    subject_concept: typing.Optional[str] = None
    device_id: typing.Optional[str] = Field(default=None, description='Name of the system, e.g., LTAMDS Gen-4')
    core_temp: typing.Optional[float] = Field(default=None, description='Overall core temperature of the system')
    uptime_hours: typing.Optional[int] = None
    anomalies: typing.List["AnomalyNode"] = Field(description='List of elements that are not nominal')

class DocumentUI(BaseModel):
    archetype: typing.Optional[types.SemanticArchetype] = Field(default=None, description='MUST be KNOWLEDGE_DOCUMENT')
    source_persona: typing.Optional[str] = Field(default=None, description='The persona that produced this data. Copy from the raw data \'persona\' field.')
    subject_concept: typing.Optional[str] = None
    markdown_content: typing.Optional[str] = None

class ExtractedIntent(BaseModel):
    mode: typing.Optional[types.Mode] = None
    candidate_verb: typing.Optional[str] = Field(default=None, description='A short verb or verb-phrase capturing what the user wants done (e.g., \'diagnose\', \'find part\', \'summarize policy\', \'build workflow\'). The supervisor matches this against r.iri and r.synonyms in the predicate graph.')
    entity_refs: typing.List[str] = Field(description='Concrete entities, parts, systems, datasets the user mentioned (e.g., \'Auxiliary Fuel Pump\', \'C-130 hydraulic system\'). Empty if the query has no specific referents.')
    confidence: typing.Optional[float] = Field(default=None, description='Confidence in the verb extraction and mode choice.')
    reasoning: typing.Optional[str] = Field(default=None, description='Why this verb and mode — for observability and debugging.')

class FinalSynthesis(BaseModel):
    markdown_report: typing.Optional[str] = None

class GraphExpertResponse(BaseModel):
    confidence_score: typing.Optional[float] = None
    referenced_uris: typing.List[str]
    data: typing.Optional[typing.Union["MechanicResponse", "AuthoringResponse", "LogisticsResponse", "AuditResponse", "DataStewardResponse"]] = None
    execution_trace: typing.Optional[str] = Field(default=None, description='The internal reasoning logs or trajectory of the agent.')

class HazardUI(BaseModel):
    archetype: typing.Optional[types.SemanticArchetype] = Field(default=None, description='MUST be HAZARD_DECLARATION')
    source_persona: typing.Optional[str] = Field(default=None, description='The persona that produced this data. Copy from the raw data \'persona\' field.')
    subject_concept: typing.Optional[str] = None
    severity: typing.Optional[types.SeverityLevel] = None
    hazards: typing.List["UIEntity"]

class KnowledgeResponse(BaseModel):
    summary: typing.Optional[str] = Field(default=None, description='A clear, professional summary answering the user\'s knowledge or policy question. Format in Markdown.')
    referenced_documents: typing.List[str] = Field(description='List of manual sections, policies, or documents cited in the summary.')
    confidence_score: typing.Optional[float] = None
    execution_trace: typing.Optional[str] = Field(default=None, description='The internal reasoning logs or trajectory of the agent.')

class LogisticsResponse(BaseModel):
    impacted_platforms: typing.List[str]
    blocked_procedures: typing.List[str]
    risk_severity: typing.Optional[str] = None

class MechanicResponse(BaseModel):
    tool_list: typing.List[str]
    safety_warnings: typing.List[str]
    short_answer: typing.Optional[str] = None

class MeshRoutingDecision(BaseModel):
    intent: typing.Optional[typing.Union[types.Intent, str]] = None
    domain: typing.Optional[typing.Union[types.Domain, str]] = None
    confidence: typing.Optional[float] = Field(default=None, description='Confidence in both intent and domain classification.')
    reasoning: typing.Optional[str] = Field(default=None, description='Why you routed it this way.')
    task_plan: typing.Optional["SupervisorTaskPlan"] = Field(default=None, description='Populate for all operational intents (queries, creation, retrieval, audits) to seed the multi-agent execution.')

class MetricUI(BaseModel):
    archetype: typing.Optional[types.SemanticArchetype] = Field(default=None, description='MUST be ASSET_STATE_METRIC')
    source_persona: typing.Optional[str] = Field(default=None, description='The persona that produced this data. Copy from the raw data \'persona\' field.')
    subject_concept: typing.Optional[str] = None
    metrics: typing.List["UIEntity"]

class SemanticResolution(BaseModel):
    # Result of mapping free-text input to a canonical sustainment concept.
# The resolved_uri is a dynamic ontology URI (not a hardcoded enum) that
# comes from the RDF graph at runtime.
    resolved_uri: typing.Optional[typing.Union[types.OntologyClass, str]] = Field(default=None, description='The ontology URI that best matches the input query. Must be one of the URIs provided in active_ontology_classes.')
    confidence_score: typing.Optional[float] = Field(default=None, description='Model confidence in the match, between 0.0 and 1.0.')
    reasoning: typing.Optional[str] = Field(default=None, description='1-2 sentence explanation of why this class was chosen.')

class SupervisorTaskPlan(BaseModel):
    tasks: typing.List["AgentTaskDefinition"]
    extracted_concepts: typing.List[str] = Field(description='List of main entities/components the user is asking about (e.g., \'Auxiliary Fuel Pump\', \'C-130\'). This populates the Ontology Map.')
    reasoning: typing.Optional[str] = None

class TableClassificationResult(BaseModel):
    resolved_uri: typing.Optional[typing.Union[types.OntologyClass, str]] = Field(default=None, description='The exact matching IOF Ontology URI, or null if uncertain/unrelated.')
    confidence_score: typing.Optional[float] = Field(default=None, description='Confidence level from 0.0 to 1.0.')
    reasoning: typing.Optional[str] = Field(default=None, description='A 1-2 sentence explanation of why this mapping was chosen based on the dossier.')

class TopologyUI(BaseModel):
    archetype: typing.Optional[types.SemanticArchetype] = Field(default=None, description='MUST be PROCESS_TOPOLOGY')
    source_persona: typing.Optional[str] = Field(default=None, description='The persona that produced this data (e.g. MECHANIC, PROCESS_ENGINEER). Copy from the raw data \'persona\' field.')
    subject_concept: typing.Optional[str] = None
    nodes: typing.List["UIEntity"]
    edges: typing.List["UIRelation"]

class UIEntity(BaseModel):
    id: typing.Optional[str] = None
    name: typing.Optional[str] = None
    type: typing.Optional[str] = None
    description: typing.Optional[str] = None

class UIRelation(BaseModel):
    source: typing.Optional[str] = None
    target: typing.Optional[str] = None
    relation: typing.Optional[str] = None
    predicate: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
