# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__

class BamlSyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def __getstate__(self):
        # Return state needed for pickling
        return {"options": self.__options}

    def __setstate__(self, state):
        # Restore state from pickling
        self.__options = state["options"]
        self.__stream_client = BamlStreamClient(self.__options)
        self.__http_request = BamlHttpRequestClient(self.__options)
        self.__http_stream_request = BamlHttpStreamRequestClient(self.__options)
        self.__llm_response_parser = LlmResponseParser(self.__options)
        self.__llm_stream_parser = LlmStreamParser(self.__options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        client: typing.Optional[str] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[typing.Callable[[str, baml_py.baml_py.FunctionLog], None]] = None,
    ) -> "BamlSyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if client is not None:
            options["client"] = client
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlSyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser

    def ClassifyDomainIntent(self, query: str,domain: str,
        baml_options: BamlCallOptions = {},
    ) -> types.SemanticResolution:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.ClassifyDomainIntent(query=query,domain=domain,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="ClassifyDomainIntent", args={
                "query": query,"domain": domain,
            })
            return typing.cast(types.SemanticResolution, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def ClassifyLegacyTable(self, table_name: str,columns_schema: str,dba_comments: str,orm_class_name: str,sample_data: str,domain: str,
        baml_options: BamlCallOptions = {},
    ) -> types.TableClassificationResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.ClassifyLegacyTable(table_name=table_name,columns_schema=columns_schema,dba_comments=dba_comments,orm_class_name=orm_class_name,sample_data=sample_data,domain=domain,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="ClassifyLegacyTable", args={
                "table_name": table_name,"columns_schema": columns_schema,"dba_comments": dba_comments,"orm_class_name": orm_class_name,"sample_data": sample_data,"domain": domain,
            })
            return typing.cast(types.TableClassificationResult, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def ClassifyPredicate(self, query: str,subject_uri: str,subject_reasoning: str,domain: str,
        baml_options: BamlCallOptions = {},
    ) -> types.PredicateClassification:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.ClassifyPredicate(query=query,subject_uri=subject_uri,subject_reasoning=subject_reasoning,domain=domain,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="ClassifyPredicate", args={
                "query": query,"subject_uri": subject_uri,"subject_reasoning": subject_reasoning,"domain": domain,
            })
            return typing.cast(types.PredicateClassification, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def DecomposeQuery(self, raw_query: str,active_personas: str,
        baml_options: BamlCallOptions = {},
    ) -> types.SupervisorTaskPlan:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.DecomposeQuery(raw_query=raw_query,active_personas=active_personas,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="DecomposeQuery", args={
                "raw_query": raw_query,"active_personas": active_personas,
            })
            return typing.cast(types.SupervisorTaskPlan, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def DesignUI(self, raw_data: str,persona: str,
        baml_options: BamlCallOptions = {},
    ) -> types.DashboardUI:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.DesignUI(raw_data=raw_data,persona=persona,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="DesignUI", args={
                "raw_data": raw_data,"persona": persona,
            })
            return typing.cast(types.DashboardUI, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractIntent(self, user_query: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ExtractedIntent:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.ExtractIntent(user_query=user_query,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractIntent", args={
                "user_query": user_query,
            })
            return typing.cast(types.ExtractedIntent, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractPlatformScope(self, user_query: str,known_platforms: str,
        baml_options: BamlCallOptions = {},
    ) -> types.PlatformScope:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.ExtractPlatformScope(user_query=user_query,known_platforms=known_platforms,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractPlatformScope", args={
                "user_query": user_query,"known_platforms": known_platforms,
            })
            return typing.cast(types.PlatformScope, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def FormatGraphResponse(self, raw_text: str,persona: str,
        baml_options: BamlCallOptions = {},
    ) -> types.GraphExpertResponse:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.FormatGraphResponse(raw_text=raw_text,persona=persona,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="FormatGraphResponse", args={
                "raw_text": raw_text,"persona": persona,
            })
            return typing.cast(types.GraphExpertResponse, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def FormatKnowledgeResponse(self, raw_text: str,domain: str,
        baml_options: BamlCallOptions = {},
    ) -> types.KnowledgeResponse:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.FormatKnowledgeResponse(raw_text=raw_text,domain=domain,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="FormatKnowledgeResponse", args={
                "raw_text": raw_text,"domain": domain,
            })
            return typing.cast(types.KnowledgeResponse, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def IterateBPMNGraph(self, chat_history: str,user_message: str,current_graph_json: str,available_ontology_classes: str,available_data_sources: str,
        baml_options: BamlCallOptions = {},
    ) -> types.BPMNInterviewState:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.IterateBPMNGraph(chat_history=chat_history,user_message=user_message,current_graph_json=current_graph_json,available_ontology_classes=available_ontology_classes,available_data_sources=available_data_sources,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="IterateBPMNGraph", args={
                "chat_history": chat_history,"user_message": user_message,"current_graph_json": current_graph_json,"available_ontology_classes": available_ontology_classes,"available_data_sources": available_data_sources,
            })
            return typing.cast(types.BPMNInterviewState, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def RenderAsChart(self, raw_data: str,persona: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ChartUI:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.RenderAsChart(raw_data=raw_data,persona=persona,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="RenderAsChart", args={
                "raw_data": raw_data,"persona": persona,
            })
            return typing.cast(types.ChartUI, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def RenderAsHazard(self, raw_data: str,persona: str,
        baml_options: BamlCallOptions = {},
    ) -> types.HazardUI:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.RenderAsHazard(raw_data=raw_data,persona=persona,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="RenderAsHazard", args={
                "raw_data": raw_data,"persona": persona,
            })
            return typing.cast(types.HazardUI, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def RenderAsMetric(self, raw_data: str,persona: str,
        baml_options: BamlCallOptions = {},
    ) -> types.MetricUI:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.RenderAsMetric(raw_data=raw_data,persona=persona,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="RenderAsMetric", args={
                "raw_data": raw_data,"persona": persona,
            })
            return typing.cast(types.MetricUI, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def RenderAsTopology(self, raw_data: str,persona: str,
        baml_options: BamlCallOptions = {},
    ) -> types.TopologyUI:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.RenderAsTopology(raw_data=raw_data,persona=persona,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="RenderAsTopology", args={
                "raw_data": raw_data,"persona": persona,
            })
            return typing.cast(types.TopologyUI, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def RouteAndPlan(self, user_query: str,
        baml_options: BamlCallOptions = {},
    ) -> types.MeshRoutingDecision:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.RouteAndPlan(user_query=user_query,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="RouteAndPlan", args={
                "user_query": user_query,
            })
            return typing.cast(types.MeshRoutingDecision, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def SynthesizeReports(self, original_query: str,raw_json_results: str,
        baml_options: BamlCallOptions = {},
    ) -> types.FinalSynthesis:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.SynthesizeReports(original_query=original_query,raw_json_results=raw_json_results,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="SynthesizeReports", args={
                "original_query": original_query,"raw_json_results": raw_json_results,
            })
            return typing.cast(types.FinalSynthesis, __result__.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ClassifyDomainIntent(self, query: str,domain: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.SemanticResolution, types.SemanticResolution]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="ClassifyDomainIntent", args={
            "query": query,"domain": domain,
        })
        return baml_py.BamlSyncStream[stream_types.SemanticResolution, types.SemanticResolution](
          __result__,
          lambda x: typing.cast(stream_types.SemanticResolution, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.SemanticResolution, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ClassifyLegacyTable(self, table_name: str,columns_schema: str,dba_comments: str,orm_class_name: str,sample_data: str,domain: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.TableClassificationResult, types.TableClassificationResult]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="ClassifyLegacyTable", args={
            "table_name": table_name,"columns_schema": columns_schema,"dba_comments": dba_comments,"orm_class_name": orm_class_name,"sample_data": sample_data,"domain": domain,
        })
        return baml_py.BamlSyncStream[stream_types.TableClassificationResult, types.TableClassificationResult](
          __result__,
          lambda x: typing.cast(stream_types.TableClassificationResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.TableClassificationResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ClassifyPredicate(self, query: str,subject_uri: str,subject_reasoning: str,domain: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.PredicateClassification, types.PredicateClassification]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="ClassifyPredicate", args={
            "query": query,"subject_uri": subject_uri,"subject_reasoning": subject_reasoning,"domain": domain,
        })
        return baml_py.BamlSyncStream[stream_types.PredicateClassification, types.PredicateClassification](
          __result__,
          lambda x: typing.cast(stream_types.PredicateClassification, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.PredicateClassification, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def DecomposeQuery(self, raw_query: str,active_personas: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.SupervisorTaskPlan, types.SupervisorTaskPlan]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="DecomposeQuery", args={
            "raw_query": raw_query,"active_personas": active_personas,
        })
        return baml_py.BamlSyncStream[stream_types.SupervisorTaskPlan, types.SupervisorTaskPlan](
          __result__,
          lambda x: typing.cast(stream_types.SupervisorTaskPlan, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.SupervisorTaskPlan, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def DesignUI(self, raw_data: str,persona: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.DashboardUI, types.DashboardUI]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="DesignUI", args={
            "raw_data": raw_data,"persona": persona,
        })
        return baml_py.BamlSyncStream[stream_types.DashboardUI, types.DashboardUI](
          __result__,
          lambda x: typing.cast(stream_types.DashboardUI, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.DashboardUI, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ExtractIntent(self, user_query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.ExtractedIntent, types.ExtractedIntent]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractIntent", args={
            "user_query": user_query,
        })
        return baml_py.BamlSyncStream[stream_types.ExtractedIntent, types.ExtractedIntent](
          __result__,
          lambda x: typing.cast(stream_types.ExtractedIntent, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ExtractedIntent, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ExtractPlatformScope(self, user_query: str,known_platforms: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.PlatformScope, types.PlatformScope]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractPlatformScope", args={
            "user_query": user_query,"known_platforms": known_platforms,
        })
        return baml_py.BamlSyncStream[stream_types.PlatformScope, types.PlatformScope](
          __result__,
          lambda x: typing.cast(stream_types.PlatformScope, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.PlatformScope, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def FormatGraphResponse(self, raw_text: str,persona: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.GraphExpertResponse, types.GraphExpertResponse]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="FormatGraphResponse", args={
            "raw_text": raw_text,"persona": persona,
        })
        return baml_py.BamlSyncStream[stream_types.GraphExpertResponse, types.GraphExpertResponse](
          __result__,
          lambda x: typing.cast(stream_types.GraphExpertResponse, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.GraphExpertResponse, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def FormatKnowledgeResponse(self, raw_text: str,domain: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.KnowledgeResponse, types.KnowledgeResponse]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="FormatKnowledgeResponse", args={
            "raw_text": raw_text,"domain": domain,
        })
        return baml_py.BamlSyncStream[stream_types.KnowledgeResponse, types.KnowledgeResponse](
          __result__,
          lambda x: typing.cast(stream_types.KnowledgeResponse, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.KnowledgeResponse, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def IterateBPMNGraph(self, chat_history: str,user_message: str,current_graph_json: str,available_ontology_classes: str,available_data_sources: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.BPMNInterviewState, types.BPMNInterviewState]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="IterateBPMNGraph", args={
            "chat_history": chat_history,"user_message": user_message,"current_graph_json": current_graph_json,"available_ontology_classes": available_ontology_classes,"available_data_sources": available_data_sources,
        })
        return baml_py.BamlSyncStream[stream_types.BPMNInterviewState, types.BPMNInterviewState](
          __result__,
          lambda x: typing.cast(stream_types.BPMNInterviewState, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.BPMNInterviewState, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def RenderAsChart(self, raw_data: str,persona: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.ChartUI, types.ChartUI]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="RenderAsChart", args={
            "raw_data": raw_data,"persona": persona,
        })
        return baml_py.BamlSyncStream[stream_types.ChartUI, types.ChartUI](
          __result__,
          lambda x: typing.cast(stream_types.ChartUI, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ChartUI, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def RenderAsHazard(self, raw_data: str,persona: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.HazardUI, types.HazardUI]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="RenderAsHazard", args={
            "raw_data": raw_data,"persona": persona,
        })
        return baml_py.BamlSyncStream[stream_types.HazardUI, types.HazardUI](
          __result__,
          lambda x: typing.cast(stream_types.HazardUI, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.HazardUI, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def RenderAsMetric(self, raw_data: str,persona: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.MetricUI, types.MetricUI]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="RenderAsMetric", args={
            "raw_data": raw_data,"persona": persona,
        })
        return baml_py.BamlSyncStream[stream_types.MetricUI, types.MetricUI](
          __result__,
          lambda x: typing.cast(stream_types.MetricUI, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.MetricUI, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def RenderAsTopology(self, raw_data: str,persona: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.TopologyUI, types.TopologyUI]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="RenderAsTopology", args={
            "raw_data": raw_data,"persona": persona,
        })
        return baml_py.BamlSyncStream[stream_types.TopologyUI, types.TopologyUI](
          __result__,
          lambda x: typing.cast(stream_types.TopologyUI, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.TopologyUI, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def RouteAndPlan(self, user_query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.MeshRoutingDecision, types.MeshRoutingDecision]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="RouteAndPlan", args={
            "user_query": user_query,
        })
        return baml_py.BamlSyncStream[stream_types.MeshRoutingDecision, types.MeshRoutingDecision](
          __result__,
          lambda x: typing.cast(stream_types.MeshRoutingDecision, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.MeshRoutingDecision, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def SynthesizeReports(self, original_query: str,raw_json_results: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.FinalSynthesis, types.FinalSynthesis]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="SynthesizeReports", args={
            "original_query": original_query,"raw_json_results": raw_json_results,
        })
        return baml_py.BamlSyncStream[stream_types.FinalSynthesis, types.FinalSynthesis](
          __result__,
          lambda x: typing.cast(stream_types.FinalSynthesis, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.FinalSynthesis, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ClassifyDomainIntent(self, query: str,domain: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ClassifyDomainIntent", args={
            "query": query,"domain": domain,
        }, mode="request")
        return __result__
    def ClassifyLegacyTable(self, table_name: str,columns_schema: str,dba_comments: str,orm_class_name: str,sample_data: str,domain: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ClassifyLegacyTable", args={
            "table_name": table_name,"columns_schema": columns_schema,"dba_comments": dba_comments,"orm_class_name": orm_class_name,"sample_data": sample_data,"domain": domain,
        }, mode="request")
        return __result__
    def ClassifyPredicate(self, query: str,subject_uri: str,subject_reasoning: str,domain: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ClassifyPredicate", args={
            "query": query,"subject_uri": subject_uri,"subject_reasoning": subject_reasoning,"domain": domain,
        }, mode="request")
        return __result__
    def DecomposeQuery(self, raw_query: str,active_personas: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="DecomposeQuery", args={
            "raw_query": raw_query,"active_personas": active_personas,
        }, mode="request")
        return __result__
    def DesignUI(self, raw_data: str,persona: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="DesignUI", args={
            "raw_data": raw_data,"persona": persona,
        }, mode="request")
        return __result__
    def ExtractIntent(self, user_query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractIntent", args={
            "user_query": user_query,
        }, mode="request")
        return __result__
    def ExtractPlatformScope(self, user_query: str,known_platforms: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractPlatformScope", args={
            "user_query": user_query,"known_platforms": known_platforms,
        }, mode="request")
        return __result__
    def FormatGraphResponse(self, raw_text: str,persona: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="FormatGraphResponse", args={
            "raw_text": raw_text,"persona": persona,
        }, mode="request")
        return __result__
    def FormatKnowledgeResponse(self, raw_text: str,domain: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="FormatKnowledgeResponse", args={
            "raw_text": raw_text,"domain": domain,
        }, mode="request")
        return __result__
    def IterateBPMNGraph(self, chat_history: str,user_message: str,current_graph_json: str,available_ontology_classes: str,available_data_sources: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="IterateBPMNGraph", args={
            "chat_history": chat_history,"user_message": user_message,"current_graph_json": current_graph_json,"available_ontology_classes": available_ontology_classes,"available_data_sources": available_data_sources,
        }, mode="request")
        return __result__
    def RenderAsChart(self, raw_data: str,persona: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="RenderAsChart", args={
            "raw_data": raw_data,"persona": persona,
        }, mode="request")
        return __result__
    def RenderAsHazard(self, raw_data: str,persona: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="RenderAsHazard", args={
            "raw_data": raw_data,"persona": persona,
        }, mode="request")
        return __result__
    def RenderAsMetric(self, raw_data: str,persona: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="RenderAsMetric", args={
            "raw_data": raw_data,"persona": persona,
        }, mode="request")
        return __result__
    def RenderAsTopology(self, raw_data: str,persona: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="RenderAsTopology", args={
            "raw_data": raw_data,"persona": persona,
        }, mode="request")
        return __result__
    def RouteAndPlan(self, user_query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="RouteAndPlan", args={
            "user_query": user_query,
        }, mode="request")
        return __result__
    def SynthesizeReports(self, original_query: str,raw_json_results: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="SynthesizeReports", args={
            "original_query": original_query,"raw_json_results": raw_json_results,
        }, mode="request")
        return __result__
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ClassifyDomainIntent(self, query: str,domain: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ClassifyDomainIntent", args={
            "query": query,"domain": domain,
        }, mode="stream")
        return __result__
    def ClassifyLegacyTable(self, table_name: str,columns_schema: str,dba_comments: str,orm_class_name: str,sample_data: str,domain: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ClassifyLegacyTable", args={
            "table_name": table_name,"columns_schema": columns_schema,"dba_comments": dba_comments,"orm_class_name": orm_class_name,"sample_data": sample_data,"domain": domain,
        }, mode="stream")
        return __result__
    def ClassifyPredicate(self, query: str,subject_uri: str,subject_reasoning: str,domain: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ClassifyPredicate", args={
            "query": query,"subject_uri": subject_uri,"subject_reasoning": subject_reasoning,"domain": domain,
        }, mode="stream")
        return __result__
    def DecomposeQuery(self, raw_query: str,active_personas: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="DecomposeQuery", args={
            "raw_query": raw_query,"active_personas": active_personas,
        }, mode="stream")
        return __result__
    def DesignUI(self, raw_data: str,persona: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="DesignUI", args={
            "raw_data": raw_data,"persona": persona,
        }, mode="stream")
        return __result__
    def ExtractIntent(self, user_query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractIntent", args={
            "user_query": user_query,
        }, mode="stream")
        return __result__
    def ExtractPlatformScope(self, user_query: str,known_platforms: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractPlatformScope", args={
            "user_query": user_query,"known_platforms": known_platforms,
        }, mode="stream")
        return __result__
    def FormatGraphResponse(self, raw_text: str,persona: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="FormatGraphResponse", args={
            "raw_text": raw_text,"persona": persona,
        }, mode="stream")
        return __result__
    def FormatKnowledgeResponse(self, raw_text: str,domain: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="FormatKnowledgeResponse", args={
            "raw_text": raw_text,"domain": domain,
        }, mode="stream")
        return __result__
    def IterateBPMNGraph(self, chat_history: str,user_message: str,current_graph_json: str,available_ontology_classes: str,available_data_sources: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="IterateBPMNGraph", args={
            "chat_history": chat_history,"user_message": user_message,"current_graph_json": current_graph_json,"available_ontology_classes": available_ontology_classes,"available_data_sources": available_data_sources,
        }, mode="stream")
        return __result__
    def RenderAsChart(self, raw_data: str,persona: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="RenderAsChart", args={
            "raw_data": raw_data,"persona": persona,
        }, mode="stream")
        return __result__
    def RenderAsHazard(self, raw_data: str,persona: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="RenderAsHazard", args={
            "raw_data": raw_data,"persona": persona,
        }, mode="stream")
        return __result__
    def RenderAsMetric(self, raw_data: str,persona: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="RenderAsMetric", args={
            "raw_data": raw_data,"persona": persona,
        }, mode="stream")
        return __result__
    def RenderAsTopology(self, raw_data: str,persona: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="RenderAsTopology", args={
            "raw_data": raw_data,"persona": persona,
        }, mode="stream")
        return __result__
    def RouteAndPlan(self, user_query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="RouteAndPlan", args={
            "user_query": user_query,
        }, mode="stream")
        return __result__
    def SynthesizeReports(self, original_query: str,raw_json_results: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="SynthesizeReports", args={
            "original_query": original_query,"raw_json_results": raw_json_results,
        }, mode="stream")
        return __result__
    

b = BamlSyncClient(DoNotUseDirectlyCallManager({}))