# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (2)
# #########################################################################

class AgentStatus(str, Enum):
    # Status returned by any agent after processing a task.
    
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    HUMAN_REQUIRED = "HUMAN_REQUIRED"

class PersonaTarget(str, Enum):
    # Target persona for the graph expert response
    
    MECHANIC = "MECHANIC"
    TECH_WRITER = "TECH_WRITER"
    LOGISTICS = "LOGISTICS"
    AUDITOR = "AUDITOR"

# #########################################################################
# Generated classes (11)
# #########################################################################

class AgentResponse(BaseModel):
    # The universal response payload returned by every agent pod.
# The Dagster orchestrator inspects this to decide on next steps
# (e.g., retry, escalate, or continue the pipeline).
    status: AgentStatus = Field(description='Outcome of the agent\'s execution.')
    summary: str = Field(description='Brief human-readable summary of what the agent did.')
    extracted_metrics: typing.Dict[str, float] = Field(description='Key-value pairs of domain metrics extracted during processing.')

class AgentTask(BaseModel):
    # The universal task payload sent from the Dagster orchestrator to any agent
# pod via HTTP POST. Every agent endpoint must accept this schema.
    task_description: str = Field(description='Human-readable description of the work the agent should perform.')
    dataset_id: str = Field(description='Identifier for the target dataset or data asset in the mesh.')
    semantic_context: typing.Optional["SemanticResolution"] = Field(default=None, description='Optional pre-resolved semantic context. When present, agents can skip their own classification step.')

class AgentTaskDefinition(BaseModel):
    target_persona: PersonaTarget
    sub_query: str

class AuditResponse(BaseModel):
    non_compliant_nodes: typing.List[str]
    rule_violated: str
    recommended_fix: str

class AuthoringResponse(BaseModel):
    generated_xml: str
    missing_info_flags: typing.List[str]

class FinalSynthesis(BaseModel):
    markdown_report: str

class GraphExpertResponse(BaseModel):
    confidence_score: float
    referenced_uris: typing.List[str]
    data: typing.Union["MechanicResponse", "AuthoringResponse", "LogisticsResponse", "AuditResponse"]

class LogisticsResponse(BaseModel):
    impacted_platforms: typing.List[str]
    blocked_procedures: typing.List[str]
    risk_severity: str

class MechanicResponse(BaseModel):
    tool_list: typing.List[str]
    safety_warnings: typing.List[str]
    short_answer: str

class SemanticResolution(BaseModel):
    # Result of mapping free-text input to a canonical sustainment concept.
# The resolved_uri is a dynamic ontology URI (not a hardcoded enum) that
# comes from the RDF graph at runtime.
    resolved_uri: str = Field(description='The ontology URI that best matches the input query. Must be one of the URIs provided in active_ontology_classes.')
    confidence_score: float = Field(description='Model confidence in the match, between 0.0 and 1.0.')
    suggested_dbt_models: typing.List[str] = Field(description='Ordered list of dbt model names relevant to the resolved concept.')

class SupervisorTaskPlan(BaseModel):
    tasks: typing.List["AgentTaskDefinition"]
    reasoning: str

# #########################################################################
# Generated type aliases (0)
# #########################################################################
