# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.AgentResponse": types.AgentResponse,
    "stream_types.AgentResponse": stream_types.AgentResponse,

    "types.AgentTask": types.AgentTask,
    "stream_types.AgentTask": stream_types.AgentTask,

    "types.AgentTaskDefinition": types.AgentTaskDefinition,
    "stream_types.AgentTaskDefinition": stream_types.AgentTaskDefinition,

    "types.AnomalyNode": types.AnomalyNode,
    "stream_types.AnomalyNode": stream_types.AnomalyNode,

    "types.AuditResponse": types.AuditResponse,
    "stream_types.AuditResponse": stream_types.AuditResponse,

    "types.AuthoringResponse": types.AuthoringResponse,
    "stream_types.AuthoringResponse": stream_types.AuthoringResponse,

    "types.BPMNEdge": types.BPMNEdge,
    "stream_types.BPMNEdge": stream_types.BPMNEdge,

    "types.BPMNInterviewState": types.BPMNInterviewState,
    "stream_types.BPMNInterviewState": stream_types.BPMNInterviewState,

    "types.BPMNNode": types.BPMNNode,
    "stream_types.BPMNNode": stream_types.BPMNNode,

    "types.ChartUI": types.ChartUI,
    "stream_types.ChartUI": stream_types.ChartUI,

    "types.DashboardUI": types.DashboardUI,
    "stream_types.DashboardUI": stream_types.DashboardUI,

    "types.DataStewardResponse": types.DataStewardResponse,
    "stream_types.DataStewardResponse": stream_types.DataStewardResponse,

    "types.DigitalTwinUI": types.DigitalTwinUI,
    "stream_types.DigitalTwinUI": stream_types.DigitalTwinUI,

    "types.DocumentUI": types.DocumentUI,
    "stream_types.DocumentUI": stream_types.DocumentUI,

    "types.ExtractedIntent": types.ExtractedIntent,
    "stream_types.ExtractedIntent": stream_types.ExtractedIntent,

    "types.FinalSynthesis": types.FinalSynthesis,
    "stream_types.FinalSynthesis": stream_types.FinalSynthesis,

    "types.GraphExpertResponse": types.GraphExpertResponse,
    "stream_types.GraphExpertResponse": stream_types.GraphExpertResponse,

    "types.HazardUI": types.HazardUI,
    "stream_types.HazardUI": stream_types.HazardUI,

    "types.KnowledgeResponse": types.KnowledgeResponse,
    "stream_types.KnowledgeResponse": stream_types.KnowledgeResponse,

    "types.LogisticsResponse": types.LogisticsResponse,
    "stream_types.LogisticsResponse": stream_types.LogisticsResponse,

    "types.MechanicResponse": types.MechanicResponse,
    "stream_types.MechanicResponse": stream_types.MechanicResponse,

    "types.MeshRoutingDecision": types.MeshRoutingDecision,
    "stream_types.MeshRoutingDecision": stream_types.MeshRoutingDecision,

    "types.MetricUI": types.MetricUI,
    "stream_types.MetricUI": stream_types.MetricUI,

    "types.SemanticResolution": types.SemanticResolution,
    "stream_types.SemanticResolution": stream_types.SemanticResolution,

    "types.SupervisorTaskPlan": types.SupervisorTaskPlan,
    "stream_types.SupervisorTaskPlan": stream_types.SupervisorTaskPlan,

    "types.TableClassificationResult": types.TableClassificationResult,
    "stream_types.TableClassificationResult": stream_types.TableClassificationResult,

    "types.TopologyUI": types.TopologyUI,
    "stream_types.TopologyUI": stream_types.TopologyUI,

    "types.UIEntity": types.UIEntity,
    "stream_types.UIEntity": stream_types.UIEntity,

    "types.UIRelation": types.UIRelation,
    "stream_types.UIRelation": stream_types.UIRelation,

    "types.VerbVerificationResult": types.VerbVerificationResult,
    "stream_types.VerbVerificationResult": stream_types.VerbVerificationResult,


    "types.AgentStatus": types.AgentStatus,

    "types.BPMNNodeType": types.BPMNNodeType,

    "types.ChartType": types.ChartType,

    "types.Domain": types.Domain,

    "types.Intent": types.Intent,

    "types.Mode": types.Mode,

    "types.MoodType": types.MoodType,

    "types.OntologyClass": types.OntologyClass,

    "types.PersonaTarget": types.PersonaTarget,

    "types.SemanticArchetype": types.SemanticArchetype,

    "types.SeverityLevel": types.SeverityLevel,

}