# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.AgentResponse": types.AgentResponse,
    "stream_types.AgentResponse": stream_types.AgentResponse,

    "types.AgentTask": types.AgentTask,
    "stream_types.AgentTask": stream_types.AgentTask,

    "types.SemanticResolution": types.SemanticResolution,
    "stream_types.SemanticResolution": stream_types.SemanticResolution,


    "types.AgentStatus": types.AgentStatus,

}