# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.AgentResponse": types.AgentResponse,
    "stream_types.AgentResponse": stream_types.AgentResponse,

    "types.AgentTask": types.AgentTask,
    "stream_types.AgentTask": stream_types.AgentTask,

    "types.AgentTaskDefinition": types.AgentTaskDefinition,
    "stream_types.AgentTaskDefinition": stream_types.AgentTaskDefinition,

    "types.AnomalyNode": types.AnomalyNode,
    "stream_types.AnomalyNode": stream_types.AnomalyNode,

    "types.AuditResponse": types.AuditResponse,
    "stream_types.AuditResponse": stream_types.AuditResponse,

    "types.AuthoringResponse": types.AuthoringResponse,
    "stream_types.AuthoringResponse": stream_types.AuthoringResponse,

    "types.BPMNEdge": types.BPMNEdge,
    "stream_types.BPMNEdge": stream_types.BPMNEdge,

    "types.BPMNInterviewState": types.BPMNInterviewState,
    "stream_types.BPMNInterviewState": stream_types.BPMNInterviewState,

    "types.BPMNNode": types.BPMNNode,
    "stream_types.BPMNNode": stream_types.BPMNNode,

    "types.CapabilityPath": types.CapabilityPath,
    "stream_types.CapabilityPath": stream_types.CapabilityPath,

    "types.ChartUI": types.ChartUI,
    "stream_types.ChartUI": stream_types.ChartUI,

    "types.CompareScenarios": types.CompareScenarios,
    "stream_types.CompareScenarios": stream_types.CompareScenarios,

    "types.CoverageGap": types.CoverageGap,
    "stream_types.CoverageGap": stream_types.CoverageGap,

    "types.DashboardUI": types.DashboardUI,
    "stream_types.DashboardUI": stream_types.DashboardUI,

    "types.DataStewardResponse": types.DataStewardResponse,
    "stream_types.DataStewardResponse": stream_types.DataStewardResponse,

    "types.DeltaEffect": types.DeltaEffect,
    "stream_types.DeltaEffect": stream_types.DeltaEffect,

    "types.DeltaSetUI": types.DeltaSetUI,
    "stream_types.DeltaSetUI": stream_types.DeltaSetUI,

    "types.DigitalTwinUI": types.DigitalTwinUI,
    "stream_types.DigitalTwinUI": stream_types.DigitalTwinUI,

    "types.DocumentUI": types.DocumentUI,
    "stream_types.DocumentUI": stream_types.DocumentUI,

    "types.DownstreamOf": types.DownstreamOf,
    "stream_types.DownstreamOf": stream_types.DownstreamOf,

    "types.ExtractedIntent": types.ExtractedIntent,
    "stream_types.ExtractedIntent": stream_types.ExtractedIntent,

    "types.FinalSynthesis": types.FinalSynthesis,
    "stream_types.FinalSynthesis": stream_types.FinalSynthesis,

    "types.GraphExpertResponse": types.GraphExpertResponse,
    "stream_types.GraphExpertResponse": stream_types.GraphExpertResponse,

    "types.HazardUI": types.HazardUI,
    "stream_types.HazardUI": stream_types.HazardUI,

    "types.IntervalRow": types.IntervalRow,
    "stream_types.IntervalRow": stream_types.IntervalRow,

    "types.KnowledgeResponse": types.KnowledgeResponse,
    "stream_types.KnowledgeResponse": stream_types.KnowledgeResponse,

    "types.LogisticsResponse": types.LogisticsResponse,
    "stream_types.LogisticsResponse": stream_types.LogisticsResponse,

    "types.MatrixCell": types.MatrixCell,
    "stream_types.MatrixCell": stream_types.MatrixCell,

    "types.MatrixGridUI": types.MatrixGridUI,
    "stream_types.MatrixGridUI": stream_types.MatrixGridUI,

    "types.MaturityGrid": types.MaturityGrid,
    "stream_types.MaturityGrid": stream_types.MaturityGrid,

    "types.MechanicResponse": types.MechanicResponse,
    "stream_types.MechanicResponse": stream_types.MechanicResponse,

    "types.MeshRoutingDecision": types.MeshRoutingDecision,
    "stream_types.MeshRoutingDecision": stream_types.MeshRoutingDecision,

    "types.MetricUI": types.MetricUI,
    "stream_types.MetricUI": stream_types.MetricUI,

    "types.MoveProject": types.MoveProject,
    "stream_types.MoveProject": stream_types.MoveProject,

    "types.NoIntentMatch": types.NoIntentMatch,
    "stream_types.NoIntentMatch": stream_types.NoIntentMatch,

    "types.NotComputableInFamily": types.NotComputableInFamily,
    "stream_types.NotComputableInFamily": stream_types.NotComputableInFamily,

    "types.PeriodSeriesRow": types.PeriodSeriesRow,
    "stream_types.PeriodSeriesRow": stream_types.PeriodSeriesRow,

    "types.PeriodSeriesUI": types.PeriodSeriesUI,
    "stream_types.PeriodSeriesUI": stream_types.PeriodSeriesUI,

    "types.PlatformScope": types.PlatformScope,
    "stream_types.PlatformScope": stream_types.PlatformScope,

    "types.PredicateClassification": types.PredicateClassification,
    "stream_types.PredicateClassification": stream_types.PredicateClassification,

    "types.ProcessEvolution": types.ProcessEvolution,
    "stream_types.ProcessEvolution": stream_types.ProcessEvolution,

    "types.ProjectsIn": types.ProjectsIn,
    "stream_types.ProjectsIn": stream_types.ProjectsIn,

    "types.SPOInterviewTurn": types.SPOInterviewTurn,
    "stream_types.SPOInterviewTurn": stream_types.SPOInterviewTurn,

    "types.SPOPick": types.SPOPick,
    "stream_types.SPOPick": stream_types.SPOPick,

    "types.SeedPortfolioCanvas": types.SeedPortfolioCanvas,
    "stream_types.SeedPortfolioCanvas": stream_types.SeedPortfolioCanvas,

    "types.SemanticResolution": types.SemanticResolution,
    "stream_types.SemanticResolution": stream_types.SemanticResolution,

    "types.SetCost": types.SetCost,
    "stream_types.SetCost": stream_types.SetCost,

    "types.ShortfallGridUI": types.ShortfallGridUI,
    "stream_types.ShortfallGridUI": stream_types.ShortfallGridUI,

    "types.ShortfallRow": types.ShortfallRow,
    "stream_types.ShortfallRow": stream_types.ShortfallRow,

    "types.ShowCostCurve": types.ShowCostCurve,
    "stream_types.ShowCostCurve": stream_types.ShowCostCurve,

    "types.ShowFundingGap": types.ShowFundingGap,
    "stream_types.ShowFundingGap": stream_types.ShowFundingGap,

    "types.ShowSiteLoad": types.ShowSiteLoad,
    "stream_types.ShowSiteLoad": stream_types.ShowSiteLoad,

    "types.SiteSchedule": types.SiteSchedule,
    "stream_types.SiteSchedule": stream_types.SiteSchedule,

    "types.SummarizeSession": types.SummarizeSession,
    "stream_types.SummarizeSession": stream_types.SummarizeSession,

    "types.SupervisorTaskPlan": types.SupervisorTaskPlan,
    "stream_types.SupervisorTaskPlan": stream_types.SupervisorTaskPlan,

    "types.TableClassificationResult": types.TableClassificationResult,
    "stream_types.TableClassificationResult": stream_types.TableClassificationResult,

    "types.TechFootprint": types.TechFootprint,
    "stream_types.TechFootprint": stream_types.TechFootprint,

    "types.ThresholdCell": types.ThresholdCell,
    "stream_types.ThresholdCell": stream_types.ThresholdCell,

    "types.ThresholdGridUI": types.ThresholdGridUI,
    "stream_types.ThresholdGridUI": stream_types.ThresholdGridUI,

    "types.TimelineUI": types.TimelineUI,
    "stream_types.TimelineUI": stream_types.TimelineUI,

    "types.TopologyUI": types.TopologyUI,
    "stream_types.TopologyUI": stream_types.TopologyUI,

    "types.UIEntity": types.UIEntity,
    "stream_types.UIEntity": stream_types.UIEntity,

    "types.UIRelation": types.UIRelation,
    "stream_types.UIRelation": stream_types.UIRelation,

    "types.WhatBlocks": types.WhatBlocks,
    "stream_types.WhatBlocks": stream_types.WhatBlocks,


    "types.AgentStatus": types.AgentStatus,

    "types.BPMNNodeType": types.BPMNNodeType,

    "types.ChartType": types.ChartType,

    "types.Domain": types.Domain,

    "types.Intent": types.Intent,

    "types.IntentFamily": types.IntentFamily,

    "types.Mode": types.Mode,

    "types.MoodType": types.MoodType,

    "types.OntologyClass": types.OntologyClass,

    "types.PersonaTarget": types.PersonaTarget,

    "types.Predicate": types.Predicate,

    "types.SPOPickAction": types.SPOPickAction,

    "types.SemanticArchetype": types.SemanticArchetype,

    "types.SeverityLevel": types.SeverityLevel,

}