# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (11)
# #########################################################################

class AgentStatus(str, Enum):
    # Status returned by any agent after processing a task.
    
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    HUMAN_REQUIRED = "HUMAN_REQUIRED"

class BPMNNodeType(str, Enum):
    ServiceTask = "ServiceTask"
    UserTask = "UserTask"
    ExclusiveGateway = "ExclusiveGateway"
    TimerEvent = "TimerEvent"

class ChartType(str, Enum):
    BAR = "BAR"
    LINE = "LINE"
    PIE = "PIE"
    SCATTER = "SCATTER"

class Domain(str, Enum):
    pass

class Intent(str, Enum):
    pass

class Mode(str, Enum):
    ONE_SHOT = "ONE_SHOT"
    CONVERSATIONAL = "CONVERSATIONAL"

class MoodType(str, Enum):
    # The visual tone or mood to pass to the frontend
    
    ROUTINE = "ROUTINE"
    URGENT = "URGENT"
    SUCCESS = "SUCCESS"
    STRATEGIC = "STRATEGIC"
    EDUCATIONAL = "EDUCATIONAL"

class OntologyClass(str, Enum):
    pass

class PersonaTarget(str, Enum):
    # Target persona for the graph expert response
    
    pass

class SemanticArchetype(str, Enum):
    PROCESS_TOPOLOGY = "PROCESS_TOPOLOGY"
    HAZARD_DECLARATION = "HAZARD_DECLARATION"
    ASSET_STATE_METRIC = "ASSET_STATE_METRIC"
    KNOWLEDGE_DOCUMENT = "KNOWLEDGE_DOCUMENT"
    CHART_WIDGET = "CHART_WIDGET"
    DIGITAL_TWIN_3D = "DIGITAL_TWIN_3D"

class SeverityLevel(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"

# #########################################################################
# Generated classes (29)
# #########################################################################

class AgentResponse(BaseModel):
    # The universal response payload returned by every agent pod.
# The Dagster orchestrator inspects this to decide on next steps
# (e.g., retry, escalate, or continue the pipeline).
    status: AgentStatus = Field(description='Outcome of the agent\'s execution.')
    summary: str = Field(description='Brief human-readable summary of what the agent did.')
    structured_data: typing.Optional[str] = Field(default=None, description='MUST be a raw JSON object/dictionary containing the actual data (e.g., lists of dashboards, chart metrics). DO NOT stringify this inside summary.')
    extracted_metrics: typing.Dict[str, float] = Field(description='Key-value pairs of domain metrics extracted during processing.')
    execution_trace: typing.Optional[str] = Field(default=None, description='The internal reasoning logs or trajectory of the agent.')

class AgentTask(BaseModel):
    # The universal task payload sent from the Dagster orchestrator to any agent
# pod via HTTP POST. Every agent endpoint must accept this schema.
    task_description: str = Field(description='Human-readable description of the work the agent should perform.')
    dataset_id: str = Field(description='Identifier for the target dataset or data asset in the mesh.')
    semantic_context: typing.Optional["SemanticResolution"] = Field(default=None, description='Optional pre-resolved semantic context. When present, agents can skip their own classification step.')
    user_id: typing.Optional[str] = Field(default=None, description='The identity of the user requesting the task, used for memory partitioning.')

class AgentTaskDefinition(BaseModel):
    target_persona: typing.Union[PersonaTarget, str]
    sub_query: str

class AnomalyNode(BaseModel):
    element_id: str = Field(description='e.g., TR-1042')
    temp: float
    status: str = Field(description='DEGRADED or CRITICAL_FAILURE')

class AuditResponse(BaseModel):
    non_compliant_nodes: typing.List[str]
    rule_violated: str
    recommended_fix: str

class AuthoringResponse(BaseModel):
    draft_content: str = Field(description='A clear, formatted Markdown summary of the requested technical data. Do NOT use XML.')
    missing_info_flags: typing.List[str] = Field(description='List of any required technical data that was missing from the graph.')

class BPMNEdge(BaseModel):
    source_id: str = Field(description='The id of the source BPMNNode.')
    target_id: str = Field(description='The id of the target BPMNNode.')
    condition_expression: typing.Optional[str] = Field(default=None, description='For edges leaving an ExclusiveGateway, the boolean condition that activates this path. Null for unconditional flows.')

class BPMNInterviewState(BaseModel):
    nodes: typing.List["BPMNNode"] = Field(description='The full list of BPMN nodes in the current graph. Updated cumulatively on each turn.')
    edges: typing.List["BPMNEdge"] = Field(description='The full list of edges connecting nodes. Updated cumulatively on each turn.')
    unresolved_paths: typing.List[str] = Field(description='Human-readable descriptions of dead-end paths, missing connections, or ambiguities that need user input to resolve. E.g. \'Gateway gw_1 has no outgoing edge for the FALSE branch.\'')
    is_ready_to_compile: bool = Field(description='True ONLY when: (1) there are zero unresolved_paths, (2) every ServiceTask has ontology_class and data_source filled, (3) the user has explicitly confirmed the workflow is complete. Default to false.')
    agent_reply: str = Field(description='Natural language response to the user. This is the conversational text shown in the Neural Stream.')

class BPMNNode(BaseModel):
    id: str = Field(description='Unique identifier for this node, e.g. \'task_1\', \'gw_1\', \'timer_1\'.')
    name: str = Field(description='Human-readable label for this node, e.g. \'Ingest Engine Telemetry\'.')
    node_type: BPMNNodeType = Field(description='The BPMN element type.')
    ontology_class: typing.Optional[str] = Field(default=None, description='IOF-MRO / MIMOSA ontology URI grounding this node. REQUIRED for ServiceTask, null for others. Must come from the available_ontology_classes list.')
    data_source: typing.Optional[str] = Field(default=None, description='DataHub / dbt model name grounding this node. REQUIRED for ServiceTask, null for others. Must come from the available_data_sources list.')

class ChartUI(BaseModel):
    archetype: SemanticArchetype = Field(description='MUST be CHART_WIDGET')
    source_persona: typing.Optional[str] = None
    subject_concept: typing.Optional[str] = None
    chart_type: ChartType
    chart_data: str = Field(description='JSON stringified array of data points for Recharts preview.')
    sql_query: str = Field(description='The raw SQL query used. Required for Superset publication.')
    superset_dataset_name: typing.Optional[str] = None
    is_published: bool

class DashboardUI(BaseModel):
    components: typing.List[typing.Union["TopologyUI", "HazardUI", "MetricUI", "DocumentUI", "ChartUI", "DigitalTwinUI"]]

class DataStewardResponse(BaseModel):
    tool_list: typing.List[str]
    safety_warnings: typing.List[str]
    short_answer: str

class DigitalTwinUI(BaseModel):
    archetype: SemanticArchetype = Field(description='MUST be DIGITAL_TWIN_3D')
    source_persona: typing.Optional[str] = None
    subject_concept: typing.Optional[str] = None
    device_id: str = Field(description='Name of the system, e.g., LTAMDS Gen-4')
    core_temp: float = Field(description='Overall core temperature of the system')
    uptime_hours: int
    anomalies: typing.List["AnomalyNode"] = Field(description='List of elements that are not nominal')

class DocumentUI(BaseModel):
    archetype: SemanticArchetype = Field(description='MUST be KNOWLEDGE_DOCUMENT')
    source_persona: typing.Optional[str] = Field(default=None, description='The persona that produced this data. Copy from the raw data \'persona\' field.')
    subject_concept: typing.Optional[str] = None
    markdown_content: str

class ExtractedIntent(BaseModel):
    mode: Mode
    entity_refs: typing.List[str] = Field(description='Concrete entities, parts, systems, datasets the user mentioned (e.g., \'Auxiliary Fuel Pump\', \'C-130 hydraulic system\'). Empty if the query has no specific referents.')
    confidence: float = Field(description='Confidence in the mode choice.')
    reasoning: str = Field(description='Why this mode — for observability and debugging.')

class FinalSynthesis(BaseModel):
    markdown_report: str

class GraphExpertResponse(BaseModel):
    confidence_score: float
    referenced_uris: typing.List[str]
    data: typing.Union["MechanicResponse", "AuthoringResponse", "LogisticsResponse", "AuditResponse", "DataStewardResponse"]
    execution_trace: typing.Optional[str] = Field(default=None, description='The internal reasoning logs or trajectory of the agent.')

class HazardUI(BaseModel):
    archetype: SemanticArchetype = Field(description='MUST be HAZARD_DECLARATION')
    source_persona: typing.Optional[str] = Field(default=None, description='The persona that produced this data. Copy from the raw data \'persona\' field.')
    subject_concept: typing.Optional[str] = None
    severity: SeverityLevel
    hazards: typing.List["UIEntity"]

class KnowledgeResponse(BaseModel):
    summary: str = Field(description='A clear, professional summary answering the user\'s knowledge or policy question. Format in Markdown.')
    referenced_documents: typing.List[str] = Field(description='List of manual sections, policies, or documents cited in the summary.')
    confidence_score: float
    execution_trace: typing.Optional[str] = Field(default=None, description='The internal reasoning logs or trajectory of the agent.')

class LogisticsResponse(BaseModel):
    impacted_platforms: typing.List[str]
    blocked_procedures: typing.List[str]
    risk_severity: str

class MechanicResponse(BaseModel):
    tool_list: typing.List[str]
    safety_warnings: typing.List[str]
    short_answer: str

class MeshRoutingDecision(BaseModel):
    intent: typing.Union[Intent, str]
    domain: typing.Union[Domain, str]
    confidence: float = Field(description='Confidence in both intent and domain classification.')
    reasoning: str = Field(description='Why you routed it this way.')
    task_plan: typing.Optional["SupervisorTaskPlan"] = Field(default=None, description='Populate for all operational intents (queries, creation, retrieval, audits) to seed the multi-agent execution.')

class MetricUI(BaseModel):
    archetype: SemanticArchetype = Field(description='MUST be ASSET_STATE_METRIC')
    source_persona: typing.Optional[str] = Field(default=None, description='The persona that produced this data. Copy from the raw data \'persona\' field.')
    subject_concept: typing.Optional[str] = None
    metrics: typing.List["UIEntity"]

class SemanticResolution(BaseModel):
    # Result of mapping free-text input to a canonical sustainment concept.
# The resolved_uri is a dynamic ontology URI (not a hardcoded enum) that
# comes from the RDF graph at runtime.
    resolved_uri: typing.Union[OntologyClass, str] = Field(description='The ontology URI that best matches the input query. Must be one of the URIs provided in active_ontology_classes.')
    confidence_score: float = Field(description='Model confidence in the match, between 0.0 and 1.0.')
    reasoning: typing.Optional[str] = Field(default=None, description='1-2 sentence explanation of why this class was chosen.')

class SupervisorTaskPlan(BaseModel):
    tasks: typing.List["AgentTaskDefinition"]
    extracted_concepts: typing.List[str] = Field(description='List of main entities/components the user is asking about (e.g., \'Auxiliary Fuel Pump\', \'C-130\'). This populates the Ontology Map.')
    reasoning: str

class TableClassificationResult(BaseModel):
    resolved_uri: typing.Optional[typing.Union[OntologyClass, str]] = Field(default=None, description='The exact matching IOF Ontology URI, or null if uncertain/unrelated.')
    confidence_score: float = Field(description='Confidence level from 0.0 to 1.0.')
    reasoning: str = Field(description='A 1-2 sentence explanation of why this mapping was chosen based on the dossier.')

class TopologyUI(BaseModel):
    archetype: SemanticArchetype = Field(description='MUST be PROCESS_TOPOLOGY')
    source_persona: typing.Optional[str] = Field(default=None, description='The persona that produced this data (e.g. MECHANIC, PROCESS_ENGINEER). Copy from the raw data \'persona\' field.')
    subject_concept: typing.Optional[str] = None
    nodes: typing.List["UIEntity"]
    edges: typing.List["UIRelation"]

class UIEntity(BaseModel):
    id: str
    name: typing.Optional[str] = None
    type: typing.Optional[str] = None
    description: typing.Optional[str] = None

class UIRelation(BaseModel):
    source: str
    target: str
    relation: typing.Optional[str] = None
    predicate: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
