apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    {{- include "invincible-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey | quote }}
  HF_TOKEN: {{ .Values.secrets.hfToken | quote }}
  DATAHUB_TOKEN: {{ .Values.secrets.datahubToken | quote }}
  BPMN_POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
