"""Rebuild a customer-validation HTML page from its .duckdb file, deterministically.

  usage: .venv/Scripts/python.exe scripts/rebuild_cost_package_from_duckdb.py \
             --duckdb dist/cost-notional-customer-alpha.duckdb \
             --out dist/rebuilt/ --like dist/cost-validation-notional-customer-alpha.html

WHAT "FROM THE DUCKDB" MEANS HERE. The recipient and the disclosed lots are READ FROM THE FILE
(its `lots` table), the page's embedded rows are generated by the engine and then CHECKED
AGAINST THE FILE BY VALUE (`datasets_agree`, inside `build_html`), and the file's sha256 goes in
the manifest. A .duckdb that does not hold the tables the engine would serve refuses the build.
The rows are not read back out of the file, because the page's figures are re-derived by the
engine's own pricing module and the file is the thing they are verified against.

WHY A SECOND SCRIPT AND NOT `build_cost_package.py` AS-IS. That CLI writes a new .duckdb, stamps
today's date and reads HEAD's sha, so two runs on two days are two different files by
construction. This one takes the two non-data inputs as arguments:

  --sha     the algorithm commit the page claims (default: HEAD, with build_cost_package's
            refusal on a dirty pricing.py)
  --as-of   the date on the page (default: required, unless --like supplies it)

and `--like FILE` reads both of those (and nothing else) out of an existing page's
`package-data` block, so "rebuild what we shipped" is one flag. Nothing else in the output is
time- or run-dependent: no timestamp, no uuid, no random, and `write_bytes` keeps line endings
as built.

WHAT CAN STILL DIFFER FROM AN EXISTING PAGE, and `--compare` says which. The page embeds
`pricing.py` and `page.py` from the WORKING TREE, so a tree that has moved since the page was
built produces a different page for the same sha argument. `--compare` reports the equal/unequal
sha256 and, when unequal, which of the page's parts differ (package-data keys, then the rest of
the page with that block removed), never the page's text.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from agent_fleet.cost_agent.seed import RECIPIENT_SCOPES, lots_for_recipient  # noqa: E402
from scripts import build_cost_package as B  # noqa: E402

_PKG = re.compile(r'(id="package-data" type="application/json">)(.*?)(</script>)', re.S)


def sha256_of(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def recipient_from_name(duckdb: pathlib.Path) -> str:
    """`cost-<recipient>.duckdb` -> `<recipient>`, validated against the engine's own scopes."""
    stem = duckdb.stem
    scope = stem[len("cost-"):] if stem.startswith("cost-") else stem
    if scope not in RECIPIENT_SCOPES:
        raise SystemExit(
            f"cannot infer a recipient from {duckdb.name!r}; pass --recipient "
            f"(known: {sorted(RECIPIENT_SCOPES)})")
    return scope


def lots_in(duckdb: pathlib.Path) -> tuple[int, ...]:
    import duckdb as _d
    con = _d.connect(str(duckdb), read_only=True)
    try:
        return tuple(r[0] for r in con.execute("SELECT lot FROM lots ORDER BY lot").fetchall())
    finally:
        con.close()


def package_data(html: str) -> dict:
    m = _PKG.search(html)
    if not m:
        raise SystemExit("no package-data block in the page")
    return json.loads(m.group(2))


def rebuild(duckdb: pathlib.Path, recipient: str, runtime_dir: pathlib.Path, *,
            sha: str, as_of: str, slice1: bool = False) -> str:
    if slice1:
        # The ONE-FILE page (no dataset block, no section markers): what the engine wrote before
        # the .duckdb shipped beside it. Same inputs, same determinism, no duckdb read.
        html = B.build_html(recipient, runtime_dir, None, sha=sha, as_of=as_of)
        problems = B.check_javascript(html)
        if problems:
            raise SystemExit("REFUSING TO WRITE: the page's JavaScript does not parse.")
        return html
    entitled = lots_for_recipient(recipient)
    in_file = lots_in(duckdb)
    if set(in_file) - set(entitled) or not in_file:
        raise SystemExit(
            f"REFUSING TO BUILD: {duckdb.name} holds lots {list(in_file)}, which are not a "
            f"non-empty subset of {recipient!r}'s {list(entitled)}")
    html = B.build_html(recipient, runtime_dir, duckdb, lots=in_file, sections=B.X.SECTIONS,
                        sha=sha, as_of=as_of)
    problems = B.check_javascript(html)
    if problems:
        raise SystemExit("REFUSING TO WRITE: the page's JavaScript does not parse.\n  "
                         + "\n  ".join(problems))
    return html


def compare(built: str, existing_path: pathlib.Path) -> int:
    """Hash equality, then WHERE the difference is, by structure."""
    old = existing_path.read_text(encoding="utf-8")
    hb, ho = sha256_of(built.encode("utf-8")), sha256_of(old.encode("utf-8"))
    print(f"compare: rebuilt {hb[:16]} ({len(built.encode('utf-8'))} B)  "
          f"existing {ho[:16]} ({len(old.encode('utf-8'))} B)")
    if hb == ho:
        print("compare: IDENTICAL")
        return 0
    pb, po = package_data(built), package_data(old)
    keys = sorted(k for k in set(pb) | set(po) if pb.get(k) != po.get(k))
    print(f"compare: package-data keys that differ: {keys or 'none'}")
    for k in keys:
        if isinstance(pb.get(k), dict) and isinstance(po.get(k), dict):
            sub = sorted(s for s in set(pb[k]) | set(po[k]) if pb[k].get(s) != po[k].get(s))
            print(f"  {k}: differing sub-keys {sub}")
    rb, ro = _PKG.sub(r"\1\3", built), _PKG.sub(r"\1\3", old)
    print(f"compare: page with package-data removed: "
          f"{'IDENTICAL' if rb == ro else 'DIFFERS'} "
          f"({sha256_of(rb.encode())[:12]} vs {sha256_of(ro.encode())[:12]})")
    if rb != ro:
        # The embedded modules are the usual cause: name the first byte offset, not the text.
        i = next((n for n, (a, b) in enumerate(zip(rb, ro)) if a != b), min(len(rb), len(ro)))
        print(f"compare: first differing offset {i} of {len(rb)} / {len(ro)}")
    return 1


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--duckdb", required=True, type=pathlib.Path)
    ap.add_argument("--recipient")
    ap.add_argument("--out", required=True, type=pathlib.Path,
                    help="DIRECTORY; the page is written as cost-validation-<recipient>.html")
    ap.add_argument("--runtime-dir", type=pathlib.Path, default=ROOT / ".pyodide-cache")
    ap.add_argument("--sha")
    ap.add_argument("--as-of")
    ap.add_argument("--like", type=pathlib.Path,
                    help="take --sha and --as-of from this existing page's package-data")
    ap.add_argument("--compare", type=pathlib.Path,
                    help="report hash equality and structural difference against this page")
    ap.add_argument("--slice1", action="store_true",
                    help="build the one-file page that carries no dataset (provenance check for pages written before the .duckdb shipped beside them)")
    ap.add_argument("--twice", action="store_true",
                    help="build a second time and require byte-identical output")
    a = ap.parse_args()

    recipient = a.recipient or recipient_from_name(a.duckdb)
    sha, as_of = a.sha, a.as_of
    if a.like:
        pkg = package_data(a.like.read_text(encoding="utf-8"))
        sha, as_of = sha or pkg["algorithm_sha"], as_of or pkg["as_of"]
    sha = sha or B.algorithm_sha()
    if not as_of:
        ap.error("--as-of is required (or --like): the page's date is an input, not a clock read")

    html = rebuild(a.duckdb, recipient, a.runtime_dir, sha=sha, as_of=as_of, slice1=a.slice1)
    data = html.encode("utf-8")
    a.out.mkdir(parents=True, exist_ok=True)
    dest = a.out / f"cost-validation-{recipient}.html"
    dest.write_bytes(data)
    print(f"wrote {dest}  {len(data)} B  sha256 {sha256_of(data)}")
    print(f"inputs: duckdb sha256 {sha256_of(a.duckdb.read_bytes())[:16]}  algorithm {sha[:12]}  "
          f"as-of {as_of}")

    rc = 0
    if a.twice:
        again = rebuild(a.duckdb, recipient, a.runtime_dir, sha=sha, as_of=as_of,
                        slice1=a.slice1).encode("utf-8")
        same = again == data
        print(f"idempotent: second build {'IDENTICAL' if same else 'DIFFERS'} "
              f"(sha256 {sha256_of(again)[:16]})")
        rc |= 0 if same else 2
    if a.compare:
        rc |= compare(html, a.compare)
    return rc


if __name__ == "__main__":
    raise SystemExit(main())
