/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  AgentResponse,  AgentStatus,  AgentTask,  AgentTaskDefinition,  AnomalyNode,  AuditResponse,  AuthoringResponse,  BPMNEdge,  BPMNInterviewState,  BPMNNode,  BPMNNodeType,  ChartType,  ChartUI,  DashboardUI,  DataStewardResponse,  DigitalTwinUI,  DocumentUI,  Domain,  FinalSynthesis,  GraphExpertResponse,  HazardUI,  Intent,  KnowledgeResponse,  LogisticsResponse,  MechanicResponse,  MeshRoutingDecision,  MetricUI,  MoodType,  PersonaTarget,  SemanticArchetype,  SemanticResolution,  SeverityLevel,  SupervisorTaskPlan,  TableClassificationResult,  TopologyUI,  UIEntity,  UIRelation } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    /**
     * The universal response payload returned by every agent pod.
 * The Dagster orchestrator inspects this to decide on next steps
 * (e.g., retry, escalate, or continue the pipeline).
    */
    export interface AgentResponse {
      status?: types.AgentStatus | null
      summary?: string | null
      structured_data?: string | null
      extracted_metrics: Record<string, number>
      execution_trace?: string | null
    }
    /**
     * The universal task payload sent from the Dagster orchestrator to any agent
 * pod via HTTP POST. Every agent endpoint must accept this schema.
    */
    export interface AgentTask {
      task_description?: string | null
      dataset_id?: string | null
      semantic_context?: SemanticResolution | null
      user_id?: string | null
    }
    export interface AgentTaskDefinition {
      target_persona?: (string | types.PersonaTarget) | null
      sub_query?: string | null
    }
    export interface AnomalyNode {
      element_id?: string | null
      temp?: number | null
      status?: string | null
    }
    export interface AuditResponse {
      non_compliant_nodes: string[]
      rule_violated?: string | null
      recommended_fix?: string | null
    }
    export interface AuthoringResponse {
      draft_content?: string | null
      missing_info_flags: string[]
    }
    export interface BPMNEdge {
      source_id?: string | null
      target_id?: string | null
      condition_expression?: string | null
    }
    export interface BPMNInterviewState {
      nodes: BPMNNode[]
      edges: BPMNEdge[]
      unresolved_paths: string[]
      is_ready_to_compile?: boolean | null
      agent_reply?: string | null
    }
    export interface BPMNNode {
      id?: string | null
      name?: string | null
      node_type?: types.BPMNNodeType | null
      ontology_class?: string | null
      data_source?: string | null
    }
    export interface ChartUI {
      archetype?: types.SemanticArchetype | null
      source_persona?: string | null
      subject_concept?: string | null
      chart_type?: types.ChartType | null
      chart_data?: string | null
      sql_query?: string | null
      superset_dataset_name?: string | null
      is_published?: boolean | null
    }
    export interface DashboardUI {
      components: (TopologyUI | HazardUI | MetricUI | DocumentUI | ChartUI | DigitalTwinUI)[]
    }
    export interface DataStewardResponse {
      tool_list: string[]
      safety_warnings: string[]
      short_answer?: string | null
    }
    export interface DigitalTwinUI {
      archetype?: types.SemanticArchetype | null
      source_persona?: string | null
      subject_concept?: string | null
      device_id?: string | null
      core_temp?: number | null
      uptime_hours?: number | null
      anomalies: AnomalyNode[]
    }
    export interface DocumentUI {
      archetype?: types.SemanticArchetype | null
      source_persona?: string | null
      subject_concept?: string | null
      markdown_content?: string | null
    }
    export interface FinalSynthesis {
      markdown_report?: string | null
    }
    export interface GraphExpertResponse {
      confidence_score?: number | null
      referenced_uris: string[]
      data?: MechanicResponse | AuthoringResponse | LogisticsResponse | AuditResponse | DataStewardResponse | null
      execution_trace?: string | null
    }
    export interface HazardUI {
      archetype?: types.SemanticArchetype | null
      source_persona?: string | null
      subject_concept?: string | null
      severity?: types.SeverityLevel | null
      hazards: UIEntity[]
    }
    export interface KnowledgeResponse {
      summary?: string | null
      referenced_documents: string[]
      confidence_score?: number | null
      execution_trace?: string | null
    }
    export interface LogisticsResponse {
      impacted_platforms: string[]
      blocked_procedures: string[]
      risk_severity?: string | null
    }
    export interface MechanicResponse {
      tool_list: string[]
      safety_warnings: string[]
      short_answer?: string | null
    }
    export interface MeshRoutingDecision {
      intent?: (string | types.Intent) | null
      domain?: (string | types.Domain) | null
      confidence?: number | null
      reasoning?: string | null
      task_plan?: SupervisorTaskPlan | null
    }
    export interface MetricUI {
      archetype?: types.SemanticArchetype | null
      source_persona?: string | null
      subject_concept?: string | null
      metrics: UIEntity[]
    }
    /**
     * Result of mapping free-text input to a canonical sustainment concept.
 * The resolved_uri is a dynamic ontology URI (not a hardcoded enum) that
 * comes from the RDF graph at runtime.
    */
    export interface SemanticResolution {
      resolved_uri?: string | null
      confidence_score?: number | null
    }
    export interface SupervisorTaskPlan {
      tasks: AgentTaskDefinition[]
      extracted_concepts: string[]
      reasoning?: string | null
    }
    export interface TableClassificationResult {
      resolved_uri?: string | null
      confidence_score?: number | null
      reasoning?: string | null
    }
    export interface TopologyUI {
      archetype?: types.SemanticArchetype | null
      source_persona?: string | null
      subject_concept?: string | null
      nodes: UIEntity[]
      edges: UIRelation[]
    }
    export interface UIEntity {
      id?: string | null
      name?: string | null
      type?: string | null
      description?: string | null
    }
    export interface UIRelation {
      source?: string | null
      target?: string | null
      relation?: string | null
      predicate?: string | null
    }
}