/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import { FieldType } from '@boundaryml/baml/native'
import { TypeBuilder as _TypeBuilder, EnumBuilder, EnumViewer, ClassBuilder, ClassViewer } from '@boundaryml/baml/type_builder'
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals"

export { FieldType, EnumBuilder, ClassBuilder }

export default class TypeBuilder {
    private tb: _TypeBuilder;
    
    AgentResponse: ClassViewer<'AgentResponse', "status" | "summary" | "structured_data" | "extracted_metrics" | "execution_trace">;
    
    AgentTask: ClassViewer<'AgentTask', "task_description" | "dataset_id" | "semantic_context" | "user_id">;
    
    AgentTaskDefinition: ClassViewer<'AgentTaskDefinition', "target_persona" | "sub_query">;
    
    AnomalyNode: ClassViewer<'AnomalyNode', "element_id" | "temp" | "status">;
    
    AuditResponse: ClassViewer<'AuditResponse', "non_compliant_nodes" | "rule_violated" | "recommended_fix">;
    
    AuthoringResponse: ClassViewer<'AuthoringResponse', "draft_content" | "missing_info_flags">;
    
    BPMNEdge: ClassViewer<'BPMNEdge', "source_id" | "target_id" | "condition_expression">;
    
    BPMNInterviewState: ClassViewer<'BPMNInterviewState', "nodes" | "edges" | "unresolved_paths" | "is_ready_to_compile" | "agent_reply">;
    
    BPMNNode: ClassViewer<'BPMNNode', "id" | "name" | "node_type" | "ontology_class" | "data_source">;
    
    ChartUI: ClassViewer<'ChartUI', "archetype" | "source_persona" | "subject_concept" | "chart_type" | "chart_data" | "sql_query" | "superset_dataset_name" | "is_published">;
    
    DashboardUI: ClassViewer<'DashboardUI', "components">;
    
    DataStewardResponse: ClassViewer<'DataStewardResponse', "tool_list" | "safety_warnings" | "short_answer">;
    
    DigitalTwinUI: ClassViewer<'DigitalTwinUI', "archetype" | "source_persona" | "subject_concept" | "device_id" | "core_temp" | "uptime_hours" | "anomalies">;
    
    DocumentUI: ClassViewer<'DocumentUI', "archetype" | "source_persona" | "subject_concept" | "markdown_content">;
    
    ExtractedIntent: ClassViewer<'ExtractedIntent', "mode" | "candidate_verb" | "entity_refs" | "confidence" | "reasoning">;
    
    FinalSynthesis: ClassViewer<'FinalSynthesis', "markdown_report">;
    
    GraphExpertResponse: ClassViewer<'GraphExpertResponse', "confidence_score" | "referenced_uris" | "data" | "execution_trace">;
    
    HazardUI: ClassViewer<'HazardUI', "archetype" | "source_persona" | "subject_concept" | "severity" | "hazards">;
    
    KnowledgeResponse: ClassViewer<'KnowledgeResponse', "summary" | "referenced_documents" | "confidence_score" | "execution_trace">;
    
    LogisticsResponse: ClassViewer<'LogisticsResponse', "impacted_platforms" | "blocked_procedures" | "risk_severity">;
    
    MechanicResponse: ClassViewer<'MechanicResponse', "tool_list" | "safety_warnings" | "short_answer">;
    
    MeshRoutingDecision: ClassViewer<'MeshRoutingDecision', "intent" | "domain" | "confidence" | "reasoning" | "task_plan">;
    
    MetricUI: ClassViewer<'MetricUI', "archetype" | "source_persona" | "subject_concept" | "metrics">;
    
    SemanticResolution: ClassViewer<'SemanticResolution', "resolved_uri" | "confidence_score" | "reasoning">;
    
    SupervisorTaskPlan: ClassViewer<'SupervisorTaskPlan', "tasks" | "extracted_concepts" | "reasoning">;
    
    TableClassificationResult: ClassViewer<'TableClassificationResult', "resolved_uri" | "confidence_score" | "reasoning">;
    
    TopologyUI: ClassViewer<'TopologyUI', "archetype" | "source_persona" | "subject_concept" | "nodes" | "edges">;
    
    UIEntity: ClassViewer<'UIEntity', "id" | "name" | "type" | "description">;
    
    UIRelation: ClassViewer<'UIRelation', "source" | "target" | "relation" | "predicate">;
    
    
    AgentStatus: EnumViewer<'AgentStatus', "SUCCESS" | "FAILED" | "HUMAN_REQUIRED">;
    
    BPMNNodeType: EnumViewer<'BPMNNodeType', "ServiceTask" | "UserTask" | "ExclusiveGateway" | "TimerEvent">;
    
    ChartType: EnumViewer<'ChartType', "BAR" | "LINE" | "PIE" | "SCATTER">;
    
    Domain: EnumBuilder<'Domain'>;
    
    Intent: EnumBuilder<'Intent'>;
    
    Mode: EnumViewer<'Mode', "ONE_SHOT" | "CONVERSATIONAL">;
    
    MoodType: EnumViewer<'MoodType', "ROUTINE" | "URGENT" | "SUCCESS" | "STRATEGIC" | "EDUCATIONAL">;
    
    OntologyClass: EnumBuilder<'OntologyClass'>;
    
    PersonaTarget: EnumBuilder<'PersonaTarget'>;
    
    SemanticArchetype: EnumViewer<'SemanticArchetype', "PROCESS_TOPOLOGY" | "HAZARD_DECLARATION" | "ASSET_STATE_METRIC" | "KNOWLEDGE_DOCUMENT" | "CHART_WIDGET" | "DIGITAL_TWIN_3D">;
    
    SeverityLevel: EnumViewer<'SeverityLevel', "INFO" | "WARNING" | "CRITICAL">;
    

    constructor() {
        this.tb = new _TypeBuilder({
          classes: new Set([
            "AgentResponse","AgentTask","AgentTaskDefinition","AnomalyNode","AuditResponse","AuthoringResponse","BPMNEdge","BPMNInterviewState","BPMNNode","ChartUI","DashboardUI","DataStewardResponse","DigitalTwinUI","DocumentUI","ExtractedIntent","FinalSynthesis","GraphExpertResponse","HazardUI","KnowledgeResponse","LogisticsResponse","MechanicResponse","MeshRoutingDecision","MetricUI","SemanticResolution","SupervisorTaskPlan","TableClassificationResult","TopologyUI","UIEntity","UIRelation",
          ]),
          enums: new Set([
            "AgentStatus","BPMNNodeType","ChartType","Domain","Intent","Mode","MoodType","OntologyClass","PersonaTarget","SemanticArchetype","SeverityLevel",
          ]),
          runtime: DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME
        });
        
        this.AgentResponse = this.tb.classViewer("AgentResponse", [
          "status","summary","structured_data","extracted_metrics","execution_trace",
        ]);
        
        this.AgentTask = this.tb.classViewer("AgentTask", [
          "task_description","dataset_id","semantic_context","user_id",
        ]);
        
        this.AgentTaskDefinition = this.tb.classViewer("AgentTaskDefinition", [
          "target_persona","sub_query",
        ]);
        
        this.AnomalyNode = this.tb.classViewer("AnomalyNode", [
          "element_id","temp","status",
        ]);
        
        this.AuditResponse = this.tb.classViewer("AuditResponse", [
          "non_compliant_nodes","rule_violated","recommended_fix",
        ]);
        
        this.AuthoringResponse = this.tb.classViewer("AuthoringResponse", [
          "draft_content","missing_info_flags",
        ]);
        
        this.BPMNEdge = this.tb.classViewer("BPMNEdge", [
          "source_id","target_id","condition_expression",
        ]);
        
        this.BPMNInterviewState = this.tb.classViewer("BPMNInterviewState", [
          "nodes","edges","unresolved_paths","is_ready_to_compile","agent_reply",
        ]);
        
        this.BPMNNode = this.tb.classViewer("BPMNNode", [
          "id","name","node_type","ontology_class","data_source",
        ]);
        
        this.ChartUI = this.tb.classViewer("ChartUI", [
          "archetype","source_persona","subject_concept","chart_type","chart_data","sql_query","superset_dataset_name","is_published",
        ]);
        
        this.DashboardUI = this.tb.classViewer("DashboardUI", [
          "components",
        ]);
        
        this.DataStewardResponse = this.tb.classViewer("DataStewardResponse", [
          "tool_list","safety_warnings","short_answer",
        ]);
        
        this.DigitalTwinUI = this.tb.classViewer("DigitalTwinUI", [
          "archetype","source_persona","subject_concept","device_id","core_temp","uptime_hours","anomalies",
        ]);
        
        this.DocumentUI = this.tb.classViewer("DocumentUI", [
          "archetype","source_persona","subject_concept","markdown_content",
        ]);
        
        this.ExtractedIntent = this.tb.classViewer("ExtractedIntent", [
          "mode","candidate_verb","entity_refs","confidence","reasoning",
        ]);
        
        this.FinalSynthesis = this.tb.classViewer("FinalSynthesis", [
          "markdown_report",
        ]);
        
        this.GraphExpertResponse = this.tb.classViewer("GraphExpertResponse", [
          "confidence_score","referenced_uris","data","execution_trace",
        ]);
        
        this.HazardUI = this.tb.classViewer("HazardUI", [
          "archetype","source_persona","subject_concept","severity","hazards",
        ]);
        
        this.KnowledgeResponse = this.tb.classViewer("KnowledgeResponse", [
          "summary","referenced_documents","confidence_score","execution_trace",
        ]);
        
        this.LogisticsResponse = this.tb.classViewer("LogisticsResponse", [
          "impacted_platforms","blocked_procedures","risk_severity",
        ]);
        
        this.MechanicResponse = this.tb.classViewer("MechanicResponse", [
          "tool_list","safety_warnings","short_answer",
        ]);
        
        this.MeshRoutingDecision = this.tb.classViewer("MeshRoutingDecision", [
          "intent","domain","confidence","reasoning","task_plan",
        ]);
        
        this.MetricUI = this.tb.classViewer("MetricUI", [
          "archetype","source_persona","subject_concept","metrics",
        ]);
        
        this.SemanticResolution = this.tb.classViewer("SemanticResolution", [
          "resolved_uri","confidence_score","reasoning",
        ]);
        
        this.SupervisorTaskPlan = this.tb.classViewer("SupervisorTaskPlan", [
          "tasks","extracted_concepts","reasoning",
        ]);
        
        this.TableClassificationResult = this.tb.classViewer("TableClassificationResult", [
          "resolved_uri","confidence_score","reasoning",
        ]);
        
        this.TopologyUI = this.tb.classViewer("TopologyUI", [
          "archetype","source_persona","subject_concept","nodes","edges",
        ]);
        
        this.UIEntity = this.tb.classViewer("UIEntity", [
          "id","name","type","description",
        ]);
        
        this.UIRelation = this.tb.classViewer("UIRelation", [
          "source","target","relation","predicate",
        ]);
        
        
        this.AgentStatus = this.tb.enumViewer("AgentStatus", [
          "SUCCESS","FAILED","HUMAN_REQUIRED",
        ]);
        
        this.BPMNNodeType = this.tb.enumViewer("BPMNNodeType", [
          "ServiceTask","UserTask","ExclusiveGateway","TimerEvent",
        ]);
        
        this.ChartType = this.tb.enumViewer("ChartType", [
          "BAR","LINE","PIE","SCATTER",
        ]);
        
        this.Domain = this.tb.enumBuilder("Domain", [
          
        ]);
        
        this.Intent = this.tb.enumBuilder("Intent", [
          
        ]);
        
        this.Mode = this.tb.enumViewer("Mode", [
          "ONE_SHOT","CONVERSATIONAL",
        ]);
        
        this.MoodType = this.tb.enumViewer("MoodType", [
          "ROUTINE","URGENT","SUCCESS","STRATEGIC","EDUCATIONAL",
        ]);
        
        this.OntologyClass = this.tb.enumBuilder("OntologyClass", [
          
        ]);
        
        this.PersonaTarget = this.tb.enumBuilder("PersonaTarget", [
          
        ]);
        
        this.SemanticArchetype = this.tb.enumViewer("SemanticArchetype", [
          "PROCESS_TOPOLOGY","HAZARD_DECLARATION","ASSET_STATE_METRIC","KNOWLEDGE_DOCUMENT","CHART_WIDGET","DIGITAL_TWIN_3D",
        ]);
        
        this.SeverityLevel = this.tb.enumViewer("SeverityLevel", [
          "INFO","WARNING","CRITICAL",
        ]);
        
    }

    reset(): void {
        this.tb.reset();
        // TODO: This should happen in Rust. Problem is, when we construct the
        // typebuilder we instantiate class builders once and it seems to make
        // a JS copy, bypassing the Rust side? In Python however, every time we
        // access a class builder with @property, we get a new instance that
        // wraps over the Rust type builder, so we only need to call tb.reset().
        // In JS it's not possible unless we refactor the way class builders are
        // accessed.
        
    }

    __tb() {
      return this.tb._tb();
    }

    string(): FieldType {
        return this.tb.string()
    }

    literalString(value: string): FieldType {
        return this.tb.literalString(value)
    }

    literalInt(value: number): FieldType {
        return this.tb.literalInt(value)
    }

    literalBool(value: boolean): FieldType {
        return this.tb.literalBool(value)
    }

    int(): FieldType {
        return this.tb.int()
    }

    float(): FieldType {
        return this.tb.float()
    }

    bool(): FieldType {
        return this.tb.bool()
    }

    list(type: FieldType): FieldType {
        return this.tb.list(type)
    }

    null(): FieldType {
        return this.tb.null()
    }

    map(key: FieldType, value: FieldType): FieldType {
        return this.tb.map(key, value)
    }

    union(types: FieldType[]): FieldType {
        return this.tb.union(types)
    }

    addClass<Name extends string>(name: Name): ClassBuilder<Name> {
        return this.tb.addClass(name);
    }

    addEnum<Name extends string>(name: Name): EnumBuilder<Name> {
        return this.tb.addEnum(name);
    }

    addBaml(baml: string): void {
        this.tb.addBaml(baml);
    }
}