/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
/**
 * Recursively partial type that can be null.
 *
 * @deprecated Use types from the `partial_types` namespace instead, which provides type-safe partial implementations
 * @template T The type to make recursively partial.
 */
export type RecursivePartialNull<T> = T extends object
    ? { [P in keyof T]?: RecursivePartialNull<T[P]> }
    : T | null;

export interface Checked<T,CheckName extends string = string> {
    value: T,
    checks: Record<CheckName, Check>,
}

export interface Check {
    name: string,
    expr: string
    status: "succeeded" | "failed"
}

export function all_succeeded<CheckName extends string>(checks: Record<CheckName, Check>): boolean {
    return get_checks(checks).every(check => check.status === "succeeded")
}

export function get_checks<CheckName extends string>(checks: Record<CheckName, Check>): Check[] {
    return Object.values(checks)
}
/**
 * Status returned by any agent after processing a task.
 */
export enum AgentStatus {
  SUCCESS = "SUCCESS",
  FAILED = "FAILED",
  HUMAN_REQUIRED = "HUMAN_REQUIRED",
}

export enum BPMNNodeType {
  ServiceTask = "ServiceTask",
  UserTask = "UserTask",
  ExclusiveGateway = "ExclusiveGateway",
  TimerEvent = "TimerEvent",
}

export enum ChartType {
  BAR = "BAR",
  LINE = "LINE",
  PIE = "PIE",
  SCATTER = "SCATTER",
}

export enum Domain {
}

export enum Intent {
}

/**
 * The visual tone or mood to pass to the frontend
 */
export enum MoodType {
  ROUTINE = "ROUTINE",
  URGENT = "URGENT",
  SUCCESS = "SUCCESS",
  STRATEGIC = "STRATEGIC",
  EDUCATIONAL = "EDUCATIONAL",
}

/**
 * Target persona for the graph expert response
 */
export enum PersonaTarget {
}

export enum SemanticArchetype {
  PROCESS_TOPOLOGY = "PROCESS_TOPOLOGY",
  HAZARD_DECLARATION = "HAZARD_DECLARATION",
  ASSET_STATE_METRIC = "ASSET_STATE_METRIC",
  KNOWLEDGE_DOCUMENT = "KNOWLEDGE_DOCUMENT",
  CHART_WIDGET = "CHART_WIDGET",
  DIGITAL_TWIN_3D = "DIGITAL_TWIN_3D",
}

export enum SeverityLevel {
  INFO = "INFO",
  WARNING = "WARNING",
  CRITICAL = "CRITICAL",
}

/**
 * The universal response payload returned by every agent pod.
 * The Dagster orchestrator inspects this to decide on next steps
 * (e.g., retry, escalate, or continue the pipeline).
 */
export interface AgentResponse {
  status: AgentStatus
  summary: string
  structured_data?: string | null
  extracted_metrics: Record<string, number>
  execution_trace?: string | null
  
}

/**
 * The universal task payload sent from the Dagster orchestrator to any agent
 * pod via HTTP POST. Every agent endpoint must accept this schema.
 */
export interface AgentTask {
  task_description: string
  dataset_id: string
  semantic_context?: SemanticResolution | null
  user_id?: string | null
  
}

export interface AgentTaskDefinition {
  target_persona: (string | PersonaTarget)
  sub_query: string
  
}

export interface AnomalyNode {
  element_id: string
  temp: number
  status: string
  
}

export interface AuditResponse {
  non_compliant_nodes: string[]
  rule_violated: string
  recommended_fix: string
  
}

export interface AuthoringResponse {
  draft_content: string
  missing_info_flags: string[]
  
}

export interface BPMNEdge {
  source_id: string
  target_id: string
  condition_expression?: string | null
  
}

export interface BPMNInterviewState {
  nodes: BPMNNode[]
  edges: BPMNEdge[]
  unresolved_paths: string[]
  is_ready_to_compile: boolean
  agent_reply: string
  
}

export interface BPMNNode {
  id: string
  name: string
  node_type: BPMNNodeType
  ontology_class?: string | null
  data_source?: string | null
  
}

export interface ChartUI {
  archetype: SemanticArchetype
  source_persona?: string | null
  subject_concept?: string | null
  chart_type: ChartType
  chart_data: string
  sql_query: string
  superset_dataset_name?: string | null
  is_published: boolean
  
}

export interface DashboardUI {
  components: (TopologyUI | HazardUI | MetricUI | DocumentUI | ChartUI | DigitalTwinUI)[]
  
}

export interface DataStewardResponse {
  tool_list: string[]
  safety_warnings: string[]
  short_answer: string
  
}

export interface DigitalTwinUI {
  archetype: SemanticArchetype
  source_persona?: string | null
  subject_concept?: string | null
  device_id: string
  core_temp: number
  uptime_hours: number
  anomalies: AnomalyNode[]
  
}

export interface DocumentUI {
  archetype: SemanticArchetype
  source_persona?: string | null
  subject_concept?: string | null
  markdown_content: string
  
}

export interface FinalSynthesis {
  markdown_report: string
  
}

export interface GraphExpertResponse {
  confidence_score: number
  referenced_uris: string[]
  data: MechanicResponse | AuthoringResponse | LogisticsResponse | AuditResponse | DataStewardResponse
  execution_trace?: string | null
  
}

export interface HazardUI {
  archetype: SemanticArchetype
  source_persona?: string | null
  subject_concept?: string | null
  severity: SeverityLevel
  hazards: UIEntity[]
  
}

export interface KnowledgeResponse {
  summary: string
  referenced_documents: string[]
  confidence_score: number
  execution_trace?: string | null
  
}

export interface LogisticsResponse {
  impacted_platforms: string[]
  blocked_procedures: string[]
  risk_severity: string
  
}

export interface MechanicResponse {
  tool_list: string[]
  safety_warnings: string[]
  short_answer: string
  
}

export interface MeshRoutingDecision {
  intent: (string | Intent)
  domain: (string | Domain)
  confidence: number
  reasoning: string
  task_plan?: SupervisorTaskPlan | null
  
}

export interface MetricUI {
  archetype: SemanticArchetype
  source_persona?: string | null
  subject_concept?: string | null
  metrics: UIEntity[]
  
}

/**
 * Result of mapping free-text input to a canonical sustainment concept.
 * The resolved_uri is a dynamic ontology URI (not a hardcoded enum) that
 * comes from the RDF graph at runtime.
 */
export interface SemanticResolution {
  resolved_uri: string
  confidence_score: number
  
}

export interface SupervisorTaskPlan {
  tasks: AgentTaskDefinition[]
  extracted_concepts: string[]
  reasoning: string
  
}

export interface TableClassificationResult {
  resolved_uri?: string | null
  confidence_score: number
  reasoning: string
  
}

export interface TopologyUI {
  archetype: SemanticArchetype
  source_persona?: string | null
  subject_concept?: string | null
  nodes: UIEntity[]
  edges: UIRelation[]
  
}

export interface UIEntity {
  id: string
  name?: string | null
  type?: string | null
  description?: string | null
  
}

export interface UIRelation {
  source: string
  target: string
  relation?: string | null
  predicate?: string | null
  
}
